'use strict';function v(e,a,b,c,g){e.v.kc(e.Va,a,b,c,g)}function x(e,a,b,c){e.v.xa?v(e,a,b,c):e.v.lf()._OnMessageFromDOM({type:"event",component:e.Va,handler:a,dispatchOpts:c||null,data:b,responseId:null})}function A(e,a,b){e.v.B(e.Va,a,b)}function B(e,a){for(const [b,c]of a)A(e,b,c)}function C(e){e.Mb||(e.v.We(e.be),e.Mb=!0)}window.bc=class{constructor(e,a){this.v=e;this.Va=a;this.Mb=!1;this.be=()=>this.qa()}dd(){}qa(){}};function D(e){-1!==e.Ma&&(self.clearTimeout(e.Ma),e.Ma=-1)}
window.Me=class{constructor(e,a){this.Jc=e;this.yg=a;this.Ma=-1;this.Nb=-Infinity;this.ce=()=>{this.Ma=-1;this.Nb=Date.now();this.$a=!0;this.Jc();this.$a=!1};this.Ld=this.$a=!1}c(){D(this);this.ce=this.Jc=null}};"use strict";function E(e,a){const b=a.elementId,c=e.pb(b,a);e.T.set(b,c);a.isVisible||(c.style.display="none");c.addEventListener("focus",()=>{F(e,"elem-focused",b)});c.addEventListener("blur",()=>{F(e,"elem-blurred",b)});e.Ua&&document.body.appendChild(c)}
function G(e,a,b){A(e,a,c=>{const g=e.T.get(c.elementId);return b(g,c)})}function F(e,a,b,c){c||(c={});c.elementId=b;v(e,a,c)}function H(e,a,b,c){c||(c={});c.elementId=b;x(e,a,c)}
window.ac=class extends self.bc{constructor(e,a){super(e,a);this.T=new Map;this.Ua=!0;B(this,[["create",b=>E(this,b)],["destroy",b=>{{b=b.elementId;const c=this.T.get(b);this.jd(c);this.Ua&&c.parentElement.removeChild(c);this.T.delete(b)}}],["set-visible",b=>{this.Ua&&(this.T.get(b.elementId).style.display=b.isVisible?"":"none")}],["update-position",b=>{if(this.Ua){var c=this.T.get(b.elementId);c.style.left=b.left+"px";c.style.top=b.top+"px";c.style.width=b.width+"px";c.style.height=b.height+"px";
b=b.fontSize;null!==b&&(c.style.fontSize=b+"em")}}],["update-state",b=>{{const c=this.T.get(b.elementId);this.Ba(c,b)}}],["focus",b=>{{const c=this.T.get(b.elementId);b.focus?c.focus():c.blur()}}],["set-css-style",b=>{this.T.get(b.elementId).style[b.prop]=b.val}],["set-attribute",b=>{this.T.get(b.elementId).setAttribute(b.name,b.val)}],["remove-attribute",b=>{this.T.get(b.elementId).removeAttribute(b.name)}]]);G(this,"get-element",b=>b)}pb(){throw Error("required override");}jd(){}Ba(){throw Error("required override");
}};"use strict";
{var I=function(q){return m.has(q)},J=function(q){return new Promise((f,k)=>{const n=new FileReader;n.onload=r=>f(r.target.result);n.onerror=r=>k(r);n.readAsArrayBuffer(q)})},K=async function(q){q=await J(q);return(new TextDecoder("utf-8")).decode(q)},L=function(q){if(q.Jg){const f=document.createElement("script");f.async=!1;f.textContent=q.Mg;document.head.appendChild(f)}else return new Promise((f,k)=>{const n=document.createElement("script");n.onload=f;n.onerror=k;n.async=!1;n.src=q;document.head.appendChild(n)})};
const e=/(iphone|ipod|ipad|macos|macintosh|mac os x)/i.test(navigator.userAgent);let a=new Audio;const b={"audio/webm; codecs=opus":!!a.canPlayType("audio/webm; codecs=opus"),"audio/ogg; codecs=opus":!!a.canPlayType("audio/ogg; codecs=opus"),"audio/webm; codecs=vorbis":!!a.canPlayType("audio/webm; codecs=vorbis"),"audio/ogg; codecs=vorbis":!!a.canPlayType("audio/ogg; codecs=vorbis"),"audio/mp4":!!a.canPlayType("audio/mp4"),"audio/mpeg":!!a.canPlayType("audio/mpeg")};a=null;const c=[];let g=0;window.RealFile=
window.File;const l=[],t=new Map,d=new Map;let h=0;const p=[];self.Wg=function(q){if("function"!==typeof q)throw Error("runOnStartup called without a function");p.push(q)};const m=new Set(["cordova","playable-ad","instant-games"]);window.Aa=class q{constructor(f){this.xa=f.Og;this.ma=null;this.X="";this.Yc=f.Lg;this.ob={};this.Fa=this.nb=null;this.Kb=[];this.bb=this.I=this.Ka=null;this.Ja=-1;this.Dg=()=>this.Jf();this.Ia=[];this.U=f.de;I(this.U)&&this.xa&&(console.warn("[C3 runtime] Worker mode is enabled and supported, but is disabled in WebViews due to crbug.com/923007. Reverting to DOM mode."),
this.xa=!1);this.ad=!1;this.Pb=this.ha=null;"html5"!==this.U&&"playable-ad"!==this.U||"file"!==location.protocol.substr(0,4)||alert("Exported games won't work until you upload them. (When running on the file: protocol, browsers block many features from working for security reasons.)");this.B("runtime","cordova-fetch-local-file",k=>this.vf(k));this.B("runtime","create-job-worker",()=>this.wf());"cordova"===this.U?document.addEventListener("deviceready",()=>this.yd(f)):this.yd(f)}c(){this.rc();this.ma&&
(this.ma=this.ma.onmessage=null);this.nb&&(this.nb.terminate(),this.nb=null);this.Fa&&(this.Fa.c(),this.Fa=null);this.I&&(this.I.parentElement.removeChild(this.I),this.I=null)}jc(){return e&&"cordova"===this.U}tb(){return e&&I(this.U)||navigator.standalone}async yd(f){if("playable-ad"===this.U){this.ha=self.c3_base64files;this.Pb={};await this.af();for(let n=0,r=f.Na.length;n<r;++n){var k=f.Na[n].toLowerCase();this.Pb.hasOwnProperty(k)?f.Na[n]={Jg:!0,Mg:this.Pb[k]}:this.ha.hasOwnProperty(k)&&(f.Na[n]=
URL.createObjectURL(this.ha[k]))}}f.Gg?this.X=f.Gg:(k=location.origin,this.X=("null"===k?"file:///":k)+location.pathname,k=this.X.lastIndexOf("/"),-1!==k&&(this.X=this.X.substr(0,k+1)));if(f.Qg)for(const [n,r]of Object.entries(f.Qg))this.ob[n]=URL.createObjectURL(r);k=new MessageChannel;this.ma=k.port1;this.ma.onmessage=n=>this._OnMessageFromRuntime(n.data);window.c3_addPortMessageHandler&&window.c3_addPortMessageHandler(n=>this.Ff(n));this.bb=new self.Ie(this);await this.bb.Ee();this.md();"object"===
typeof window.StatusBar&&window.StatusBar.hide();"object"===typeof window.AndroidFullScreen&&window.AndroidFullScreen.immersiveMode();await this.rg();this.xa?await this.pf(f,k.port2):await this.nf(f,k.port2)}uc(f){return this.ob.hasOwnProperty(f)?this.ob[f]:f.endsWith("/workermain.js")&&this.ob.hasOwnProperty("workermain.js")?this.ob["workermain.js"]:"playable-ad"===this.U&&this.ha.hasOwnProperty(f.toLowerCase())?URL.createObjectURL(this.ha[f.toLowerCase()]):f}async $b(f,k,n){if(f.startsWith("blob:"))return new Worker(f,
n);if(this.jc()&&"file:"===location.protocol)return f=await this.Zb(this.Yc+f),new Worker(URL.createObjectURL(new Blob([f],{type:"application/javascript"})),n);f=new URL(f,k);if(location.origin!==f.origin){f=await fetch(f);if(!f.ok)throw Error("failed to fetch worker script");f=await f.blob();return new Worker(URL.createObjectURL(f),n)}return new Worker(f,n)}md(){if(this.tb()){const f=document.documentElement.style,k=document.body.style,n=window.innerWidth<window.innerHeight,r=n?window.screen.width:
window.screen.height;k.height=f.height=(n?window.screen.height:window.screen.width)+"px";k.width=f.width=r+"px"}}wd(f){return{baseUrl:this.X,windowInnerWidth:window.innerWidth,windowInnerHeight:window.innerHeight,devicePixelRatio:window.devicePixelRatio,isFullscreen:q.ic(),projectData:f.Vg,previewImageBlobs:window.cr_previewImageBlobs||this.ha,previewProjectFileBlobs:window.cr_previewProjectFileBlobs,exportType:f.de,isDebug:-1<self.location.search.indexOf("debug"),ife:!!self.Ug,jobScheduler:this.bb.Ce(),
supportedAudioFormats:b,opusWasmScriptUrl:window.cr_opusWasmScriptUrl||this.Yc+"opus.wasm.js",opusWasmBinaryUrl:window.cr_opusWasmBinaryUrl||this.Yc+"opus.wasm.wasm",isiOSCordova:this.jc(),isiOSWebView:this.tb(),isFBInstantAvailable:"undefined"!==typeof self.FBInstant}}async pf(f,k){var n=this.uc(f.Pg);this.nb=await this.$b(n,this.X,{name:"Runtime"});this.I=document.createElement("canvas");this.I.style.display="none";n=this.I.transferControlToOffscreen();document.body.appendChild(this.I);window.c3canvas=
this.I;this.nb.postMessage(Object.assign(this.wd(f),{type:"init-runtime",isInWorker:!0,messagePort:k,canvas:n,workerDependencyScripts:f.cd||[],engineScripts:f.Na,projectScripts:window.Tg,projectScriptsStatus:self.C3_ProjectScriptsStatus}),[k,n,...this.bb.De()]);this.Kb=l.map(r=>new r(this));this.vd();self.c3_callFunction=(r,u)=>this.Ka.qf(r,u);"preview"===this.U&&(self.goToLastErrorScript=()=>this.kc("runtime","go-to-last-error-script"))}async nf(f,k){this.I=document.createElement("canvas");this.I.style.display=
"none";document.body.appendChild(this.I);window.c3canvas=this.I;this.Kb=l.map(r=>new r(this));this.vd();const n=f.Na.map(r=>"string"===typeof r?(new URL(r,this.X)).toString():r);Array.isArray(f.cd)&&n.unshift(...f.cd);await Promise.all(n.map(r=>L(r)));if(f.ee&&0<f.ee.length){const r=self.C3_ProjectScriptsStatus;try{if(await Promise.all(f.ee.map(u=>L(u[1]))),Object.values(r).some(u=>!u)){self.setTimeout(()=>this.Gd(r),100);return}}catch(u){console.error("[Preview] Error loading project scripts: ",
u);self.setTimeout(()=>this.Gd(r),100);return}}"preview"===this.U&&"object"!==typeof self.Rg.Sg?(console.error("[C3 runtime] Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax."),alert("Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax.")):(f=Object.assign(this.wd(f),{isInWorker:!1,messagePort:k,canvas:this.I,runOnStartupFunctions:p}),this.Fa=self.C3_CreateRuntime(f),await self.C3_InitRuntime(this.Fa,f))}Gd(f){f=
`Failed to load project script '${Object.entries(f).filter(k=>!k[1]).map(k=>k[0])[0]}'. Check all your JavaScript code has valid syntax.`;console.error("[Preview] "+f);alert(f)}async wf(){const f=await this.bb.ud();return{outputPort:f,transferables:[f]}}lf(){if(this.xa)throw Error("not available in worker mode");return this.Fa}kc(f,k,n,r,u){this.ma.postMessage({type:"event",component:f,handler:k,dispatchOpts:r||null,data:n,responseId:null},this.ad?void 0:u)}nd(f,k,n,r,u){const y=h++,w=new Promise((z,
Y)=>{d.set(y,{resolve:z,reject:Y})});this.ma.postMessage({type:"event",component:f,handler:k,dispatchOpts:r||null,data:n,responseId:y},this.ad?void 0:u);return w}["_OnMessageFromRuntime"](f){const k=f.type;if("event"===k)return this.Bf(f);if("result"===k)this.Mf(f);else if("runtime-ready"===k)this.Nf();else if("alert"===k)alert(f.message);else throw Error(`unknown message '${k}'`);}Bf(f){const k=f.component,n=f.handler,r=f.data,u=f.responseId;if(f=t.get(k))if(f=f.get(n)){var y=null;try{y=f(r)}catch(w){console.error(`Exception in '${k}' handler '${n}':`,
w);null!==u&&this.Db(u,!1,""+w);return}if(null===u)return y;y&&y.then?y.then(w=>this.Db(u,!0,w)).catch(w=>{console.error(`Rejection from '${k}' handler '${n}':`,w);this.Db(u,!1,""+w)}):this.Db(u,!0,y)}else console.warn(`[DOM] No handler '${n}' for component '${k}'`);else console.warn(`[DOM] No event handlers for component '${k}'`)}Db(f,k,n){let r;n&&n.transferables&&(r=n.transferables);this.ma.postMessage({type:"result",responseId:f,isOk:k,result:n},r)}Mf(f){const k=f.responseId,n=f.isOk;f=f.result;
const r=d.get(k);n?r.resolve(f):r.reject(f);d.delete(k)}B(f,k,n){let r=t.get(f);r||(r=new Map,t.set(f,r));if(r.has(k))throw Error(`[DOM] Component '${f}' already has handler '${k}'`);r.set(k,n)}static Oa(f){if(l.includes(f))throw Error("DOM handler already added");l.push(f)}vd(){for(const f of this.Kb)if("runtime"===f.Va){this.Ka=f;return}throw Error("cannot find runtime DOM handler");}Ff(f){this.kc("debugger","message",f)}Nf(){for(const f of this.Kb)f.dd()}static ic(){return!!(document.fullscreenElement||
document.webkitFullscreenElement||document.mozFullScreenElement)}We(f){this.Ia.push(f);this.Gc()}Yf(f){f=this.Ia.indexOf(f);if(-1===f)throw Error("invalid callback");this.Ia.splice(f,1);this.Ia.length||this.rc()}Gc(){-1===this.Ja&&this.Ia.length&&(this.Ja=requestAnimationFrame(this.Dg))}rc(){-1!==this.Ja&&(cancelAnimationFrame(this.Ja),this.Ja=-1)}Jf(){this.Ja=-1;for(const f of this.Ia)f();this.Gc()}ra(f){this.Ka.ra(f)}za(f){this.Ka.za(f)}Fc(){this.Ka.Fc()}wb(f){this.Ka.wb(f)}Ge(){return!!b["audio/webm; codecs=opus"]}async wg(f){f=
await this.nd("runtime","opus-decode",{arrayBuffer:f},null,[f]);return new Float32Array(f)}Fe(f){return/^(?:[a-z]+:)?\/\//.test(f)||"data:"===f.substr(0,5)||"blob:"===f.substr(0,5)}He(f){return!this.Fe(f)}async vf(f){const k=f.filename;switch(f.as){case "text":return await this.ve(k);case "buffer":return await this.Zb(k);default:throw Error("unsupported type");}}xd(){const f=window.cordova&&window.cordova.plugins&&window.cordova.plugins.permissions;if("object"!==typeof f)throw Error("Permission API is not loaded");
return f}Ad(f,k){f=f[k];if("string"!==typeof f)throw Error("Invalid permission name");return f}mf(f){const k=this.xd();return new Promise((n,r)=>k.checkPermission(this.Ad(k,f),u=>n(!!u.hasPermission),r))}Zf(f){const k=this.xd();return new Promise((n,r)=>k.requestPermission(this.Ad(k,f),u=>n(!!u.hasPermission),r))}async Pe(f){if("cordova"!==this.U||this.jc())return!0;for(const k of f)if(!await this.mf(k)&&!1===await this.Zf(k))return!1;return!0}async mc(...f){if(!1===await this.Pe(f))throw Error("Permission not granted");
}gd(f){const k=window.cordova.file.applicationDirectory+"www/"+f.toLowerCase();return new Promise((n,r)=>{window.resolveLocalFileSystemURL(k,u=>{u.file(n,r)},r)})}async ve(f){f=await this.gd(f);return await K(f)}sc(){if(c.length&&!(8<=g)){g++;var f=c.shift();this.bf(f.filename,f.Ng,f.Ig)}}Zb(f){return new Promise((k,n)=>{c.push({filename:f,Ng:r=>{g--;this.sc();k(r)},Ig:r=>{g--;this.sc();n(r)}});this.sc()})}async bf(f,k,n){try{const r=await this.gd(f),u=await J(r);k(u)}catch(r){n(r)}}async af(){const f=
[];for(const [k,n]of Object.entries(this.ha))f.push(this.$e(k,n));await Promise.all(f)}async $e(f,k){if("object"===typeof k)this.ha[f]=new Blob([k.str],{type:k.type}),this.Pb[f]=k.str;else{let n=await this.jf(k);n||(n=this.df(k));this.ha[f]=n}}async jf(f){try{return await (await fetch(f)).blob()}catch(k){return console.warn("Failed to fetch a data: URI. Falling back to a slower workaround. This is probably because the Content Security Policy unnecessarily blocked it. Allow data: URIs in your CSP to avoid this.",
k),null}}df(f){f=this.Sf(f);return this.Ze(f.data,f.Kg)}Sf(f){var k=f.indexOf(",");if(0>k)throw new URIError("expected comma in data: uri");var n=f.substring(k+1);k=f.substring(5,k).split(";");f=k[0]||"";const r=k[2];n="base64"===k[1]||"base64"===r?atob(n):decodeURIComponent(n);return{Kg:f,data:n}}Ze(f,k){var n=f.length;let r=n>>2,u=new Uint8Array(n),y=new Uint32Array(u.buffer,0,r),w,z;for(z=w=0;w<r;++w)y[w]=f.charCodeAt(z++)|f.charCodeAt(z++)<<8|f.charCodeAt(z++)<<16|f.charCodeAt(z++)<<24;for(n&=
3;n--;)u[z]=f.charCodeAt(z),++z;return new Blob([u],{type:k})}rg(){let f=null;const k=new Promise(u=>f=u),n=new ArrayBuffer(1),r=new MessageChannel;r.port2.onmessage=u=>{u.data&&u.data.arrayBuffer||(this.ad=!0,console.warn("MessageChannel transfers determined to be broken. Disabling transferables."));f()};r.port1.postMessage({arrayBuffer:n},[n]);return k}}}"use strict";
{var N=function(){const d=document.activeElement;if(!d)return!1;const h=d.tagName.toLowerCase(),p=new Set("email number password search tel text url".split(" "));return"textarea"===h?!0:"input"===h?p.has(d.type.toLowerCase()||"text"):M(d)},aa=function(){try{return window.parent&&window.parent.document.hasFocus()}catch(d){return!1}},O=function(d){(d.metaKey||d.ctrlKey)&&d.preventDefault()},P=function(d){l.has(d.target.tagName.toLowerCase())&&d.preventDefault()},M=function(d){do{if(d.parentNode&&d.hasAttribute("contenteditable"))return!0;
d=d.parentNode}while(d);return!1},ca=async function(d,h,p){if(!/firefox/i.test(navigator.userAgent))return await Q(d);var m=await ba(d);m=(new DOMParser).parseFromString(m,"image/svg+xml");const q=m.documentElement;if(q.hasAttribute("width")&&q.hasAttribute("height")){const f=q.getAttribute("width"),k=q.getAttribute("height");if(!f.includes("%")&&!k.includes("%"))return await Q(d)}q.setAttribute("width",h+"px");q.setAttribute("height",p+"px");m=(new XMLSerializer).serializeToString(m);d=new Blob([m],
{type:"image/svg+xml"});return await Q(d)},ba=function(d){return new Promise((h,p)=>{let m=new FileReader;m.onload=q=>h(q.target.result);m.onerror=q=>p(q);m.readAsText(d)})},Q=async function(d){d=URL.createObjectURL(d);try{return await da(d)}finally{URL.revokeObjectURL(d)}},da=function(d){return new Promise((h,p)=>{const m=new Image;m.onload=()=>h(m);m.onerror=q=>p(q);m.src=d})},ea=function(d){return new Promise((h,p)=>{const m=document.createElement("link");m.onload=()=>h(m);m.onerror=q=>p(q);m.rel=
"stylesheet";m.href=d;document.head.appendChild(m)})},R=function(d){return d.sourceCapabilities&&d.sourceCapabilities.firesTouchEvents||d.originalEvent&&d.originalEvent.sourceCapabilities&&d.originalEvent.sourceCapabilities.firesTouchEvents};const e=self.Aa,a=new Map([["OSLeft","MetaLeft"],["OSRight","MetaRight"]]),b={dispatchRuntimeEvent:!0,dispatchUserScriptEvent:!0},c={dispatchUserScriptEvent:!0},g={dispatchRuntimeEvent:!0},l=new Set(["canvas","body","html"]);self.C3_GetSvgImageSize=async function(d){d=
await Q(d);if(0<d.width&&0<d.height)return[d.width,d.height];{d.style.position="absolute";d.style.left="0px";d.style.top="0px";d.style.visibility="hidden";document.body.appendChild(d);const h=d.getBoundingClientRect();document.body.removeChild(d);return[h.width,h.height]}};self.C3_RasterSvgImageBlob=async function(d,h,p,m,q){d=await ca(d,h,p);const f=document.createElement("canvas");f.width=m;f.height=q;f.getContext("2d").drawImage(d,0,0,h,p);return f};let t=!1;document.addEventListener("pause",()=>
t=!0);document.addEventListener("resume",()=>t=!1);e.Oa(class extends self.bc{constructor(d){super(d,"runtime");this.Qd=!0;this.La=-1;this.Zc="any";this.Hd=this.Id=!1;this.Sc=this.kb=this.ta=null;d.B("canvas","update-size",m=>this.Qf(m));d.B("runtime","invoke-download",m=>this.Ef(m));d.B("runtime","raster-svg-image",m=>this.Kf(m));d.B("runtime","get-svg-image-size",m=>this.Df(m));d.B("runtime","set-target-orientation",m=>this.Of(m));d.B("runtime","register-sw",()=>this.Lf());d.B("runtime","post-to-debugger",
m=>this.Cd(m));d.B("runtime","go-to-script",m=>this.Cd(m));d.B("runtime","before-start-ticking",()=>this.uf());d.B("runtime","debug-highlight",m=>this.xf(m));d.B("runtime","enable-device-orientation",()=>this.Ye());d.B("runtime","enable-device-motion",()=>this.Xe());d.B("runtime","add-stylesheet",m=>this.sf(m));d.B("runtime","alert",m=>this.tf(m));const h=new Set(["input","textarea","datalist"]);window.addEventListener("contextmenu",m=>{const q=m.target;h.has(q.tagName.toLowerCase())||M(q)||m.preventDefault()});
const p=d.I;window.addEventListener("selectstart",P);window.addEventListener("gesturehold",P);p.addEventListener("selectstart",P);p.addEventListener("gesturehold",P);window.addEventListener("touchstart",P,{passive:!1});"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",P,{passive:!1}),p.addEventListener("pointerdown",P)):p.addEventListener("touchstart",P);this.hb=0;window.addEventListener("mousedown",m=>{1===m.button&&m.preventDefault()});window.addEventListener("mousewheel",
O,{passive:!1});window.addEventListener("wheel",O,{passive:!1});window.addEventListener("resize",()=>this.Rf());d.tb()&&window.addEventListener("focusout",()=>{N()||(document.scrollingElement.scrollTop=0)});this.Ga=new Set;this.Qb=new WeakSet;this.la=!1}uf(){"cordova"===this.v.U?(document.addEventListener("pause",()=>this.Ec(!0)),document.addEventListener("resume",()=>this.Ec(!1))):document.addEventListener("visibilitychange",()=>this.Ec(document.hidden));return{isSuspended:!(!document.hidden&&!t)}}dd(){window.addEventListener("focus",
()=>this.Eb("window-focus"));window.addEventListener("blur",()=>{this.Eb("window-blur",{parentHasFocus:aa()});this.hb=0});window.addEventListener("fullscreenchange",()=>this.zc());window.addEventListener("webkitfullscreenchange",()=>this.zc());window.addEventListener("mozfullscreenchange",()=>this.zc());window.addEventListener("fullscreenerror",h=>this.Ac(h));window.addEventListener("webkitfullscreenerror",h=>this.Ac(h));window.addEventListener("mozfullscreenerror",h=>this.Ac(h));window.addEventListener("keydown",
h=>this.Bd("keydown",h));window.addEventListener("keyup",h=>this.Bd("keyup",h));window.addEventListener("dblclick",h=>this.Cc("dblclick",h,b));window.addEventListener("wheel",h=>this.Hf(h));"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",h=>{this.vc(h);this.Sa("pointerdown",h)}),this.v.xa&&"undefined"!==typeof window.onpointerrawupdate&&self===self.top?(this.kb=new self.Me(()=>this.gf(),5),this.kb.Ld=!0,window.addEventListener("pointerrawupdate",h=>this.If(h))):window.addEventListener("pointermove",
h=>this.Sa("pointermove",h)),window.addEventListener("pointerup",h=>this.Sa("pointerup",h)),window.addEventListener("pointercancel",h=>this.Sa("pointercancel",h))):(window.addEventListener("mousedown",h=>{this.vc(h);this.Dc("pointerdown",h)}),window.addEventListener("mousemove",h=>this.Dc("pointermove",h)),window.addEventListener("mouseup",h=>this.Dc("pointerup",h)),window.addEventListener("touchstart",h=>{this.vc(h);this.Cb("pointerdown",h)}),window.addEventListener("touchmove",h=>this.Cb("pointermove",
h)),window.addEventListener("touchend",h=>this.Cb("pointerup",h)),window.addEventListener("touchcancel",h=>this.Cb("pointercancel",h)));const d=()=>this.Fc();window.addEventListener("pointerup",d,!0);window.addEventListener("touchend",d,!0);window.addEventListener("click",d,!0);window.addEventListener("keydown",d,!0);window.addEventListener("gamepadconnected",d,!0)}Eb(d,h){v(this,d,h||null,g)}Ab(){return Math.max(window.innerWidth,1)}zb(){return Math.max(window.innerHeight,1)}Rf(){const d=this.Ab(),
h=this.zb();this.Eb("window-resize",{innerWidth:d,innerHeight:h,devicePixelRatio:window.devicePixelRatio});this.v.tb()&&(-1!==this.La&&clearTimeout(this.La),this.Dd(d,h,0))}$f(d,h,p){-1!==this.La&&clearTimeout(this.La);this.La=setTimeout(()=>this.Dd(d,h,p),48)}Dd(d,h,p){const m=this.Ab(),q=this.zb();this.La=-1;m!=d||q!=h?this.Eb("window-resize",{innerWidth:m,innerHeight:q,devicePixelRatio:window.devicePixelRatio}):10>p&&this.$f(m,q,p+1)}Of(d){this.Zc=d.targetOrientation}sg(){const d=this.Zc;if(screen.orientation&&
screen.orientation.lock)screen.orientation.lock(d).catch(h=>console.warn("[Construct 3] Failed to lock orientation: ",h));else try{let h=!1;screen.lockOrientation?h=screen.lockOrientation(d):screen.webkitLockOrientation?h=screen.webkitLockOrientation(d):screen.mozLockOrientation?h=screen.mozLockOrientation(d):screen.msLockOrientation&&(h=screen.msLockOrientation(d));h||console.warn("[Construct 3] Failed to lock orientation")}catch(h){console.warn("[Construct 3] Failed to lock orientation: ",h)}}zc(){const d=
e.ic();d&&"any"!==this.Zc&&this.sg();v(this,"fullscreenchange",{isFullscreen:d,innerWidth:this.Ab(),innerHeight:this.zb()})}Ac(d){console.warn("[Construct 3] Fullscreen request failed: ",d);v(this,"fullscreenerror",{isFullscreen:e.ic(),innerWidth:this.Ab(),innerHeight:this.zb()})}Ec(d){d?this.v.rc():this.v.Gc();v(this,"visibilitychange",{hidden:d})}Bd(d,h){"Backspace"===h.key&&P(h);const p=a.get(h.code)||h.code;x(this,d,{code:p,key:h.key,which:h.which,repeat:h.repeat,altKey:h.altKey,ctrlKey:h.ctrlKey,
metaKey:h.metaKey,shiftKey:h.shiftKey,timeStamp:h.timeStamp},b)}Hf(d){v(this,"wheel",{clientX:d.clientX,clientY:d.clientY,pageX:d.pageX,pageY:d.pageY,deltaX:d.deltaX,deltaY:d.deltaY,deltaZ:d.deltaZ,deltaMode:d.deltaMode,timeStamp:d.timeStamp},b)}Cc(d,h,p){R(h)||x(this,d,{button:h.button,buttons:h.buttons,clientX:h.clientX,clientY:h.clientY,pageX:h.pageX,pageY:h.pageY,timeStamp:h.timeStamp},p)}Dc(d,h){if(!R(h)){var p=this.hb;"pointerdown"===d&&0!==p?d="pointermove":"pointerup"===d&&0!==h.buttons&&
(d="pointermove");x(this,d,{pointerId:1,pointerType:"mouse",button:h.button,buttons:h.buttons,lastButtons:p,clientX:h.clientX,clientY:h.clientY,pageX:h.pageX,pageY:h.pageY,width:0,height:0,pressure:0,tangentialPressure:0,tiltX:0,tiltY:0,twist:0,timeStamp:h.timeStamp},b);this.hb=h.buttons;this.Cc(h.type,h,c)}}Sa(d,h){if(this.kb&&"pointermove"!==d){var p=this.kb;p.$a||(D(p),p.Nb=Date.now())}p=0;"mouse"===h.pointerType&&(p=this.hb);x(this,d,{pointerId:h.pointerId,pointerType:h.pointerType,button:h.button,
buttons:h.buttons,lastButtons:p,clientX:h.clientX,clientY:h.clientY,pageX:h.pageX,pageY:h.pageY,width:h.width||0,height:h.height||0,pressure:h.pressure||0,tangentialPressure:h.tangentialPressure||0,tiltX:h.tiltX||0,tiltY:h.tiltY||0,twist:h.twist||0,timeStamp:h.timeStamp},b);"mouse"===h.pointerType&&(p="mousemove","pointerdown"===d?p="mousedown":"pointerup"===d&&(p="pointerup"),this.Cc(p,h,c),this.hb=h.buttons)}If(d){this.Sc=d;d=this.kb;if(-1===d.Ma){var h=Date.now(),p=h-d.Nb,m=d.yg;p>=m&&d.Ld?(d.Nb=
h,d.$a=!0,d.Jc(),d.$a=!1):d.Ma=self.setTimeout(d.ce,Math.max(m-p,4))}}gf(){this.Sa("pointermove",this.Sc);this.Sc=null}Cb(d,h){for(let p=0,m=h.changedTouches.length;p<m;++p){const q=h.changedTouches[p];x(this,d,{pointerId:q.identifier,pointerType:"touch",button:0,buttons:0,lastButtons:0,clientX:q.clientX,clientY:q.clientY,pageX:q.pageX,pageY:q.pageY,width:2*(q.radiusX||q.webkitRadiusX||0),height:2*(q.radiusY||q.webkitRadiusY||0),pressure:q.force||q.webkitForce||0,tangentialPressure:0,tiltX:0,tiltY:0,
twist:q.rotationAngle||0,timeStamp:h.timeStamp},b)}}vc(d){window!==window.top&&window.focus();this.zd(d.target)&&document.activeElement&&!this.zd(document.activeElement)&&document.activeElement.blur()}zd(d){return!d||d===document||d===window||d===document.body||"canvas"===d.tagName.toLowerCase()}Ye(){this.Id||(this.Id=!0,window.addEventListener("deviceorientation",d=>this.zf(d)),window.addEventListener("deviceorientationabsolute",d=>this.Af(d)))}Xe(){this.Hd||(this.Hd=!0,window.addEventListener("devicemotion",
d=>this.yf(d)))}zf(d){v(this,"deviceorientation",{absolute:!!d.absolute,alpha:d.alpha||0,beta:d.beta||0,gamma:d.gamma||0,timeStamp:d.timeStamp,webkitCompassHeading:d.webkitCompassHeading,webkitCompassAccuracy:d.webkitCompassAccuracy},b)}Af(d){v(this,"deviceorientationabsolute",{absolute:!!d.absolute,alpha:d.alpha||0,beta:d.beta||0,gamma:d.gamma||0,timeStamp:d.timeStamp},b)}yf(d){let h=null;var p=d.acceleration;p&&(h={x:p.x||0,y:p.y||0,z:p.z||0});p=null;var m=d.accelerationIncludingGravity;m&&(p={x:m.x||
0,y:m.y||0,z:m.z||0});m=null;const q=d.rotationRate;q&&(m={alpha:q.alpha||0,beta:q.beta||0,gamma:q.gamma||0});v(this,"devicemotion",{acceleration:h,accelerationIncludingGravity:p,rotationRate:m,interval:d.interval,timeStamp:d.timeStamp},b)}Qf(d){const h=this.v,p=h.I;p.style.width=d.styleWidth+"px";p.style.height=d.styleHeight+"px";p.style.marginLeft=d.marginLeft+"px";p.style.marginTop=d.marginTop+"px";h.md();this.Qd&&(p.style.display="",this.Qd=!1)}Ef(d){const h=d.url;d=d.filename;const p=document.createElement("a"),
m=document.body;p.textContent=d;p.href=h;p.download=d;m.appendChild(p);p.click();m.removeChild(p)}async Kf(d){var h=d.imageBitmapOpts;d=await self.C3_RasterSvgImageBlob(d.blob,d.imageWidth,d.imageHeight,d.surfaceWidth,d.surfaceHeight);h=h?await createImageBitmap(d,h):await createImageBitmap(d);return{imageBitmap:h,transferables:[h]}}async Df(d){return await self.C3_GetSvgImageSize(d.blob)}async sf(d){await ea(d.url)}Fc(){var d=[...this.Ga];this.Ga.clear();if(!this.la)for(const h of d)(d=h.play())&&
d.catch(()=>{this.Qb.has(h)||this.Ga.add(h)})}ra(d){if("function"!==typeof d.play)throw Error("missing play function");this.Qb.delete(d);let h;try{h=d.play()}catch(p){this.Ga.add(d);return}h&&h.catch(()=>{this.Qb.has(d)||this.Ga.add(d)})}za(d){this.Ga.delete(d);this.Qb.add(d)}wb(d){this.la=!!d}xf(d){if(d.show){this.ta||(this.ta=document.createElement("div"),this.ta.id="inspectOutline",document.body.appendChild(this.ta));var h=this.ta;h.style.display="";h.style.left=d.left-1+"px";h.style.top=d.top-
1+"px";h.style.width=d.width+2+"px";h.style.height=d.height+2+"px";h.textContent=d.name}else this.ta&&(this.ta.style.display="none")}Lf(){window.C3_RegisterSW&&window.C3_RegisterSW()}Cd(d){window.c3_postToMessagePort&&(d.from="runtime",window.c3_postToMessagePort(d))}qf(d,h){return this.v.nd(this.Va,"js-invoke-function",{name:d,params:h},void 0,void 0)}tf(d){alert(d.message)}})}"use strict";
{const e=document.currentScript.src;self.Ie=class{constructor(a){this.Ub=a;this.X=e?e.substr(0,e.lastIndexOf("/")+1):a.X;this.Ag=Math.min(navigator.hardwareConcurrency||2,16);this.Lc=null;this.Sd=[];this.Wc=this.Pc=null}async Ee(){if(this.xg)throw Error("already initialised");this.xg=!0;var a=this.Ub.uc("dispatchworker.js");this.Lc=await this.Ub.$b(a,this.X,{name:"DispatchWorker"});a=new MessageChannel;this.Pc=a.port1;this.Lc.postMessage({type:"_init","in-port":a.port2},[a.port2]);this.Wc=await this.ud()}async ud(){const a=
this.Sd.length;var b=this.Ub.uc("jobworker.js");b=await this.Ub.$b(b,this.X,{name:"JobWorker"+a});const c=new MessageChannel,g=new MessageChannel;this.Lc.postMessage({type:"_addJobWorker",port:c.port1},[c.port1]);b.postMessage({type:"init",number:a,"dispatch-port":c.port2,"output-port":g.port2},[c.port2,g.port2]);this.Sd.push(b);return g.port1}Ce(){return{inputPort:this.Pc,outputPort:this.Wc,maxNumWorkers:this.Ag}}De(){return[this.Pc,this.Wc]}}}"use strict";
window.C3_IsSupported&&(window.c3_runtimeInterface=new self.Aa({Og:"undefined"!==typeof OffscreenCanvas,Pg:"workermain.js",Na:["scripts/c3runtime.js"],Lg:"scripts/",cd:[],de:"html5"}));"use strict";
{const e=180/Math.PI;self.da=class extends self.bc{constructor(a){super(a,"audio");this.Jb=this.f=null;this.Lb=this.Oc=!1;this.na=()=>this.tg();this.ba=[];this.C=[];this.ga=null;this.Td="";this.Ud=-1;this.jb=new Map;this.Tc=1;this.la=!1;this.$c=0;this.Wb=1;this.Mc=0;this.Wd="HRTF";this.Md="inverse";this.Xd=600;this.Vd=1E4;this.Zd=1;this.Od=this.Xc=!1;this.Fg=this.v.Ge();this.ca=new Map;this.Da=new Set;this.Qc=!1;this.Uc="";this.va=null;self.C3Audio_OnMicrophoneStream=(b,c)=>this.Gf(b,c);this.Ib=null;
self.C3Audio_GetOutputStream=()=>this.Cf();self.C3Audio_DOMInterface=this;B(this,[["create-audio-context",b=>this.cf(b)],["play",b=>this.Tf(b)],["stop",b=>this.Hc(b)],["stop-all",()=>this.qg()],["set-paused",b=>this.jg(b)],["set-volume",b=>this.og(b)],["fade-volume",b=>this.hf(b)],["set-master-volume",b=>this.hg(b)],["set-muted",b=>this.ig(b)],["set-silent",b=>this.lg(b)],["set-looping",b=>this.gg(b)],["set-playback-rate",b=>this.kg(b)],["seek",b=>this.ag(b)],["preload",b=>this.Uf(b)],["unload",b=>
this.ug(b)],["unload-all",()=>this.vg()],["set-suspended",b=>this.mg(b)],["add-effect",b=>this.sd(b)],["set-effect-param",b=>this.dg(b)],["remove-effects",b=>this.Wf(b)],["tick",b=>this.Pf(b)],["load-state",b=>this.Bc(b)]])}async cf(a){a.isiOSCordova&&(this.Xc=!0);this.$c=a.timeScaleMode;this.Wd=["equalpower","HRTF","soundfield"][a.panningModel];this.Md=["linear","inverse","exponential"][a.distanceModel];this.Xd=a.refDistance;this.Vd=a.maxDistance;this.Zd=a.rolloffFactor;var b={latencyHint:a.latencyHint};
if("undefined"!==typeof AudioContext)this.f=new AudioContext(b);else if("undefined"!==typeof webkitAudioContext)this.f=new webkitAudioContext(b);else throw Error("Web Audio API not supported");this.td();this.f.onstatechange=()=>{"running"!==this.f.state&&this.td()};this.Jb=this.f.createGain();this.Jb.connect(this.f.destination);b=a.listenerPos;this.f.listener.setPosition(b[0],b[1],b[2]);this.f.listener.setOrientation(0,0,1,0,-1,0);self.C3_GetAudioContextCurrentTime=()=>this.cc();try{await Promise.all(a.preloadList.map(c=>
this.yb(c.originalUrl,c.url,c.type,!1)))}catch(c){console.error("[Construct 3] Preloading sounds failed: ",c)}return{sampleRate:this.f.sampleRate}}td(){this.Lb||(this.Oc=!1,window.addEventListener("pointerup",this.na,!0),window.addEventListener("touchend",this.na,!0),window.addEventListener("click",this.na,!0),window.addEventListener("keydown",this.na,!0),this.Lb=!0)}ef(){this.Lb&&(this.Oc=!0,window.removeEventListener("pointerup",this.na,!0),window.removeEventListener("touchend",this.na,!0),window.removeEventListener("click",
this.na,!0),window.removeEventListener("keydown",this.na,!0),this.Lb=!1)}tg(){if(!this.Oc){var a=this.f;"suspended"===a.state&&a.resume&&a.resume();var b=a.createBuffer(1,220,22050),c=a.createBufferSource();c.buffer=b;c.connect(a.destination);c.start(0);"running"===a.state&&this.ef()}}W(){return this.f}cc(){return this.f.currentTime}oa(){return this.Jb}kd(a){return(a=this.ca.get(a.toLowerCase()))?a[0].N():this.oa()}fe(a,b){a=a.toLowerCase();let c=this.ca.get(a);c||(c=[],this.ca.set(a,c));b.fg(c.length);
b.ng(a);c.push(b);this.Fd(a)}Fd(a){let b=this.oa();const c=this.ca.get(a);if(c&&c.length){b=c[0].N();for(let g=0,l=c.length;g<l;++g){const t=c[g];g+1===l?t.P(this.oa()):t.P(c[g+1].N())}}for(const g of this.ja(a))g.Ne(b);this.va&&this.Uc===a&&(this.va.disconnect(),this.va.connect(b))}rb(){return this.Tc}sb(){return this.la}eg(){this.Od=!0}xe(a,b){return b?this.v.wg(a).then(c=>{const g=this.f.createBuffer(1,c.length,48E3);g.getChannelData(0).set(c);return g}):new Promise((c,g)=>{this.f.decodeAudioData(a,
c,g)})}ra(a){this.v.ra(a)}za(a){this.v.za(a)}od(a){let b=0;for(let c=0,g=this.C.length;c<g;++c){const l=this.C[c];this.C[b]=l;l.J===a?l.c():++b}this.C.length=b}Oe(){let a=0;for(let b=0,c=this.ba.length;b<c;++b){const g=this.ba[b];this.ba[a]=g;g.pa()?g.c():++a}this.ba.length=a}*ja(a){if(a)for(const b of this.C)self.da.ye(b.$,a)&&(yield b);else this.ga&&!this.ga.R()&&(yield this.ga)}async yb(a,b,c,g,l){for(const t of this.ba)if(t.Qa()===b)return await S(t),t;if(l)return null;g&&(this.Xc||this.Od)&&
this.Oe();l="audio/webm; codecs=opus"===c&&!this.Fg;g&&l&&this.eg();a=!g||this.Xc||l?new self.te(this,a,b,c,g,l):new self.re(this,a,b,c,g);this.ba.push(a);await S(a);return a}async tc(a,b,c,g,l){for(const t of this.C)if(t.Qa()===b&&(t.Yb()||l))return t.Re(g),t;a=await this.yb(a,b,c,l);g="html5"===a.Ic?new self.se(a.i,a,g):new self.ue(a.i,a,g);this.C.push(g);return g}Ve(a){let b=this.jb.get(a);if(!b){let c=null;b={bd:0,promise:new Promise(g=>c=g),resolve:c};this.jb.set(a,b)}b.bd++}Xf(a){const b=this.jb.get(a);
if(!b)throw Error("expected pending tag");b.bd--;0===b.bd&&(b.resolve(),this.jb.delete(a))}qc(a){a||(a=this.Td);return(a=this.jb.get(a))?a.promise:Promise.resolve()}Bb(){if(0<this.Da.size)C(this);else for(const a of this.C)if(a.ld()){C(this);break}}qa(){for(var a of this.Da)a.qa();a=this.cc();for(var b of this.C)b.qa(a);b=this.C.filter(c=>c.ld()).map(c=>c.Pa());v(this,"state",{tickCount:this.Ud,audioInstances:b,analysers:[...this.Da].map(c=>c.Ae())});0===b.length&&0===this.Da.size&&this.Mb&&(this.v.Yf(this.be),
this.Mb=!1)}lc(a,b,c){v(this,"trigger",{type:a,tag:b,aiid:c})}async Tf(a){const b=a.originalUrl,c=a.url,g=a.type,l=a.isMusic,t=a.tag,d=a.isLooping,h=a.vol,p=a.pos,m=a.panning;let q=a.off;0<q&&!a.trueClock&&(this.f.getOutputTimestamp?(a=this.f.getOutputTimestamp(),q=q-a.performanceTime/1E3+a.contextTime):q=q-performance.now()/1E3+this.f.currentTime);this.Td=t;this.Ve(t);try{this.ga=await this.tc(b,c,g,t,l),m?(this.ga.vb(!0),this.ga.Qe(m.x,m.y,m.angle,m.innerAngle,m.outerAngle,m.outerGain),m.hasOwnProperty("uid")&&
this.ga.Se(m.uid)):this.ga.vb(!1),this.ga.Play(d,h,p,q)}catch(f){console.error("[Construct 3] Audio: error starting playback: ",f);return}finally{this.Xf(t)}C(this)}Hc(a){a=a.tag;for(const b of this.ja(a))b.ka()}qg(){for(const a of this.C)a.ka()}jg(a){const b=a.tag;a=a.paused;for(const c of this.ja(b))a?c.Ra():c.ub();this.Bb()}og(a){const b=a.tag;a=a.vol;for(const c of this.ja(b))c.xb(a)}async hf(a){const b=a.tag,c=a.vol,g=a.duration;a=a.stopOnEnd;await this.qc(b);for(const l of this.ja(b))l.ze(c,
g,a);this.Bb()}hg(a){this.Tc=a.vol;for(const b of this.C)b.Gb()}ig(a){const b=a.tag;a=a.isMuted;for(const c of this.ja(b))c.pd(a)}lg(a){this.la=a.isSilent;this.v.wb(this.la);for(const b of this.C)b.Fb()}gg(a){const b=a.tag;a=a.isLooping;for(const c of this.ja(b))c.oc(a)}async kg(a){const b=a.tag;a=a.rate;await this.qc(b);for(const c of this.ja(b))c.rd(a)}async ag(a){const b=a.tag;a=a.pos;await this.qc(b);for(const c of this.ja(b))c.nc(a)}async Uf(a){const b=a.originalUrl,c=a.url,g=a.type;a=a.isMusic;
try{await this.tc(b,c,g,"",a)}catch(l){console.error("[Construct 3] Audio: error preloading: ",l)}}async ug(a){if(a=await this.yb("",a.url,a.type,a.isMusic,!0))a.c(),a=this.ba.indexOf(a),-1!==a&&this.ba.splice(a,1)}vg(){for(const a of this.ba)a.c();this.ba.length=0}mg(a){a=a.isSuspended;!a&&this.f.resume&&this.f.resume();for(const b of this.C)b.pc(a);a&&this.f.suspend&&this.f.suspend()}Pf(a){this.Wb=a.timeScale;this.Mc=a.gameTime;this.Ud=a.tickCount;if(0!==this.$c)for(var b of this.C)b.Ca();(b=a.listenerPos)&&
this.f.listener.setPosition(b[0],b[1],b[2]);for(const c of a.instPans){a=c.uid;for(const g of this.C)g.fa===a&&g.qd(c.x,c.y,c.angle)}}async sd(a){var b=a.type;const c=a.tag;var g=a.params;if("filter"===b)g=new self.le(this,...g);else if("delay"===b)g=new self.je(this,...g);else if("convolution"===b){b=null;try{b=await this.yb(a.bufferOriginalUrl,a.bufferUrl,a.bufferType,!1)}catch(l){console.log("[Construct 3] Audio: error loading convolution: ",l);return}g=new self.ie(this,b.aa,...g);g.bg(a.bufferOriginalUrl,
a.bufferType)}else if("flanger"===b)g=new self.me(this,...g);else if("phaser"===b)g=new self.oe(this,...g);else if("gain"===b)g=new self.ne(this,...g);else if("tremolo"===b)g=new self.qe(this,...g);else if("ringmod"===b)g=new self.pe(this,...g);else if("distortion"===b)g=new self.ke(this,...g);else if("compressor"===b)g=new self.he(this,...g);else if("analyser"===b)g=new self.ge(this,...g);else throw Error("invalid effect type");this.fe(c,g);this.Ed()}dg(a){const b=a.index,c=a.param,g=a.value,l=a.ramp,
t=a.time;a=this.ca.get(a.tag);!a||0>b||b>=a.length||(a[b].Y(c,g,l,t),this.Ed())}Wf(a){a=a.tag.toLowerCase();const b=this.ca.get(a);if(b&&b.length){for(const c of b)c.c();this.ca.delete(a);this.Fd(a)}}Ue(a){this.Da.add(a);this.Bb()}Vf(a){this.Da.delete(a)}Ed(){this.Qc||(this.Qc=!0,Promise.resolve().then(()=>this.ff()))}ff(){const a={};for(const [b,c]of this.ca)a[b]=c.map(g=>g.Pa());v(this,"fxstate",{fxstate:a});this.Qc=!1}async Bc(a){const b=a.saveLoadMode;if(3!==b)for(var c of this.C)c.pa()&&1===
b||(c.pa()||2!==b)&&c.ka();for(const g of this.ca.values())for(const l of g)l.c();this.ca.clear();this.Wb=a.timeScale;this.Mc=a.gameTime;c=a.listenerPos;this.f.listener.setPosition(c[0],c[1],c[2]);this.la=a.isSilent;this.v.wb(this.la);this.Tc=a.masterVolume;c=[];for(const g of Object.values(a.effects))c.push(Promise.all(g.map(l=>this.sd(l))));await Promise.all(c);await Promise.all(a.playing.map(g=>this.rf(g,b)));this.Bb()}async rf(a,b){if(3!==b){var c=a.bufferOriginalUrl,g=a.bufferUrl,l=a.bufferType,
t=a.isMusic,d=a.tag,h=a.isLooping,p=a.volume,m=a.playbackTime;if(!t||1!==b)if(t||2!==b){b=null;try{b=await this.tc(c,g,l,d,t)}catch(q){console.error("[Construct 3] Audio: error loading audio state: ",q);return}b.Le(a.pan);b.Play(h,p,m,0);a.isPlaying||b.Ra();b.xc(a)}}}Gf(a,b){this.va&&this.va.disconnect();this.Uc=b.toLowerCase();this.va=this.f.createMediaStreamSource(a);this.va.connect(this.kd(this.Uc))}Cf(){this.Ib||(this.Ib=this.f.createMediaStreamDestination(),this.Jb.connect(this.Ib));return this.Ib.stream}static ye(a,
b){return a.length!==b.length?!1:a===b?!0:a.toLowerCase()===b.toLowerCase()}static Te(a){return a*e}static we(a){return Math.pow(10,a/20)}static hd(a){return Math.max(Math.min(self.da.we(a),1),0)}static Ke(a){return Math.log(a)/Math.log(10)*20}static Je(a){return self.da.Ke(Math.max(Math.min(a,1),0))}static Hg(a,b){return 1-Math.exp(-b*a)}};self.Aa.Oa(self.da)}"use strict";function S(e){e.Ob||(e.Ob=e.wc());return e.Ob}
self.ed=class{constructor(e,a,b,c,g){this.i=e;this.Cg=a;this.wa=b;this.O=c;this.zg=g;this.Ic="";this.Ob=null}c(){this.Ob=this.i=null}wc(){}W(){return this.i.W()}ec(){return this.Cg}Qa(){return this.wa}dc(){return this.O}pa(){return this.zg}ea(){}};"use strict";
self.re=class extends self.ed{constructor(e,a,b,c,g){super(e,a,b,c,g);this.Ic="html5";this.H=new Audio;this.H.crossOrigin="anonymous";this.H.autoplay=!1;this.H.preload="auto";this.cb=this.eb=null;this.H.addEventListener("canplaythrough",()=>!0);this.ib=this.W().createGain();this.gb=null;this.H.addEventListener("canplay",()=>{this.eb&&(this.eb(),this.cb=this.eb=null);!this.gb&&this.H&&(this.gb=this.W().createMediaElementSource(this.H),this.gb.connect(this.ib))});this.onended=null;this.H.addEventListener("ended",
()=>{if(this.onended)this.onended()});this.H.addEventListener("error",l=>{console.error(`[Construct 3] Audio '${this.wa}' error: `,l);this.cb&&(this.cb(l),this.cb=this.eb=null)})}c(){this.i.od(this);this.ib.disconnect();this.ib=null;this.gb.disconnect();this.gb=null;this.H&&!this.H.paused&&this.H.pause();this.H=this.onended=null;super.c()}wc(){return new Promise((e,a)=>{this.eb=e;this.cb=a;this.H.src=this.wa})}M(){return this.H}ea(){return this.H.duration}};"use strict";
async function fa(e){if(e.sa)return e.sa;var a=e.i.v;if("cordova"===a.U&&a.He(e.wa)&&"file:"===location.protocol)e.sa=await a.Zb(e.wa);else{a=await fetch(e.wa);if(!a.ok)throw Error(`error fetching audio data: ${a.status} ${a.statusText}`);e.sa=await a.arrayBuffer()}}async function ha(e){if(e.aa)return e.aa;e.aa=await e.i.xe(e.sa,e.Bg);e.sa=null}
self.te=class extends self.ed{constructor(e,a,b,c,g,l){super(e,a,b,c,g);this.Ic="webaudio";this.aa=this.sa=null;this.Bg=!!l}c(){this.i.od(this);this.aa=this.sa=null;super.c()}async wc(){try{await fa(this),await ha(this)}catch(e){console.error(`[Construct 3] Failed to load audio '${this.wa}': `,e)}}ea(){return this.aa?this.aa.duration:0}};"use strict";
{let e=0;self.fd=class{constructor(a,b,c){this.i=a;this.J=b;this.$=c;this.Hb=e++;this.K=this.W().createGain();this.K.connect(this.oa());this.A=null;this.ab=!1;this.F=!0;this.V=this.ia=this.D=!1;this.mb=1;this.Ea=!1;this.Z=1;a=this.i.$c;this.Rc=1===a&&!this.pa()||2===a;this.Ya=this.fa=-1;this.ae=!1}c(){this.J=this.i=null;this.A&&(this.A.disconnect(),this.A=null);this.K.disconnect();this.K=null}W(){return this.i.W()}oa(){return this.i.kd(this.$)}rb(){return this.i.rb()}qb(){return this.Rc?this.i.Mc:
performance.now()/1E3}ec(){return this.J.ec()}Qa(){return this.J.Qa()}dc(){return this.J.dc()}pa(){return this.J.pa()}Re(a){this.$=a}R(){}Yb(){}IsPlaying(){return!this.F&&!this.D&&!this.R()}ld(){return!this.F&&!this.R()}ya(){}ea(){return this.J.ea()}Play(){}ka(){}Ra(){}ub(){}xb(a){this.mb=a;this.K.gain.cancelScheduledValues(0);this.Ya=-1;this.K.gain.value=this.fc()}ze(a,b,c){if(!this.Ea){a*=this.rb();var g=this.K.gain;g.cancelScheduledValues(0);var l=this.i.cc();b=l+b;g.setValueAtTime(g.value,l);
g.linearRampToValueAtTime(a,b);this.mb=a;this.Ya=b;this.ae=c}}Gb(){this.xb(this.mb)}qa(a){-1!==this.Ya&&a>=this.Ya&&(this.Ya=-1,this.ae&&this.ka(),this.i.lc("fade-ended",this.$,this.Hb))}fc(){const a=this.mb*this.rb();return isFinite(a)?a:0}pd(a){a=!!a;this.Ea!==a&&(this.Ea=a,this.Fb())}sb(){return this.i.sb()}Fb(){}oc(){}rd(a){this.Z!==a&&(this.Z=a,this.Ca())}Ca(){}nc(){}pc(){}vb(a){a=!!a;this.ab!==a&&((this.ab=a)?(this.A||(this.A=this.W().createPanner(),this.A.panningModel=this.i.Wd,this.A.distanceModel=
this.i.Md,this.A.refDistance=this.i.Xd,this.A.maxDistance=this.i.Vd,this.A.rolloffFactor=this.i.Zd),this.K.disconnect(),this.K.connect(this.A),this.A.connect(this.oa())):(this.A.disconnect(),this.K.disconnect(),this.K.connect(this.oa())))}Qe(a,b,c,g,l,t){this.ab&&(this.qd(a,b,c),a=self.da.Te,this.A.coneInnerAngle=a(g),this.A.coneOuterAngle=a(l),this.A.coneOuterGain=t)}qd(a,b,c){this.ab&&(this.A.setPosition(a,b,0),this.A.setOrientation(Math.cos(c),Math.sin(c),0))}Se(a){this.fa=a}hc(){}Ne(a){const b=
this.A||this.K;b.disconnect();b.connect(a)}Pa(){return{aiid:this.Hb,tag:this.$,duration:this.ea(),volume:this.mb,isPlaying:this.IsPlaying(),playbackTime:this.ya(),playbackRate:this.Z,uid:this.fa,bufferOriginalUrl:this.ec(),bufferUrl:"",bufferType:this.dc(),isMusic:this.pa(),isLooping:this.V,isMuted:this.Ea,resumePosition:this.hc(),pan:this.Be()}}xc(a){this.rd(a.playbackRate);this.pd(a.isMuted)}Be(){if(!this.A)return null;const a=this.A;return{pos:[a.positionX.value,a.positionY.value,a.positionZ.value],
orient:[a.orientationX.value,a.orientationY.value,a.orientationZ.value],cia:a.coneInnerAngle,coa:a.coneOuterAngle,cog:a.coneOuterGain,uid:this.fa}}Le(a){a?(this.vb(!0),a=this.A,a.setPosition(...a.pos),a.setOrientation(...a.orient),a.coneInnerAngle=a.cia,a.coneOuterAngle=a.coa,a.coneOuterGain=a.cog,this.fa=a.uid):this.vb(!1)}}}"use strict";
self.se=class extends self.fd{constructor(e,a,b){super(e,a,b);this.J.ib.connect(this.K);this.J.onended=()=>this.yc()}c(){this.ka();this.J.ib.disconnect();super.c()}M(){return this.J.M()}yc(){this.F=!0;this.fa=-1;this.i.lc("ended",this.$,this.Hb)}R(){return this.M().ended}Yb(){return this.F?!0:this.R()}ya(e){let a=this.M().currentTime;e&&(a*=this.Z);this.V||(a=Math.min(a,this.ea()));return a}Play(e,a,b){const c=this.M();1!==c.playbackRate&&(c.playbackRate=1);c.loop!==e&&(c.loop=e);this.xb(a);c.muted&&
(c.muted=!1);if(c.currentTime!==b)try{c.currentTime=b}catch(g){console.warn(`[Construct 3] Exception seeking audio '${this.J.Qa()}' to position '${b}': `,g)}this.i.ra(c);this.D=this.F=!1;this.V=e;this.Z=1}ka(){const e=this.M();e.paused||e.pause();this.i.za(e);this.F=!0;this.D=!1;this.fa=-1}Ra(){if(!(this.D||this.F||this.R())){var e=this.M();e.paused||e.pause();this.i.za(e);this.D=!0}}ub(){!this.D||this.F||this.R()||(this.i.ra(this.M()),this.D=!1)}Fb(){this.M().muted=this.Ea||this.sb()}oc(e){e=!!e;
this.V!==e&&(this.V=e,this.M().loop=e)}Ca(){let e=this.Z;this.Rc&&(e*=this.i.Wb);try{this.M().playbackRate=e}catch(a){console.warn(`[Construct 3] Unable to set playback rate '${e}':`,a)}}nc(e){if(!this.F&&!this.R())try{this.M().currentTime=e}catch(a){console.warn(`[Construct 3] Error seeking audio to '${e}': `,a)}}hc(){return this.ya()}pc(e){e?this.IsPlaying()?(this.M().pause(),this.ia=!0):this.ia=!1:this.ia&&(this.i.ra(this.M()),this.ia=!1)}};"use strict";
function T(e){e.j&&e.j.disconnect();e.j=null;e.Ta=null}
self.ue=class extends self.fd{constructor(e,a,b){super(e,a,b);this.j=null;this.Rb=c=>this.yc(c);this.Nc=!0;this.Ta=null;this.L=this.Vb=0;this.Vc=1}c(){this.ka();T(this);this.Rb=null;super.c()}yc(e){this.D||this.ia||e.target!==this.Ta||(this.F=this.Nc=!0,this.fa=-1,T(this),this.i.lc("ended",this.$,this.Hb))}R(){return!this.F&&this.j&&this.j.loop||this.D?!1:this.Nc}Yb(){return!this.j||this.F?!0:this.R()}ya(e){let a;a=this.D?this.L:this.qb()-this.Vb;e&&(a*=this.Z);this.V||(a=Math.min(a,this.ea()));return a}Play(e,
a,b,c){this.Vc=1;this.xb(a);T(this);this.j=this.W().createBufferSource();this.j.buffer=this.J.aa;this.j.connect(this.K);this.Ta=this.j;this.j.onended=this.Rb;this.j.loop=e;this.j.start(c,b);this.D=this.F=this.Nc=!1;this.V=e;this.Z=1;this.Vb=this.qb()-b}ka(){if(this.j)try{this.j.stop(0)}catch(e){}this.F=!0;this.D=!1;this.fa=-1}Ra(){this.D||this.F||this.R()||(this.L=this.ya(!0),this.V&&(this.L%=this.ea()),this.D=!0,this.j.stop(0))}ub(){!this.D||this.F||this.R()||(T(this),this.j=this.W().createBufferSource(),
this.j.buffer=this.J.aa,this.j.connect(this.K),this.Ta=this.j,this.j.onended=this.Rb,this.j.loop=this.V,this.Gb(),this.Ca(),this.Vb=this.qb()-this.L/(this.Z||.001),this.j.start(0,this.L),this.D=!1)}fc(){return super.fc()*this.Vc}Fb(){this.Vc=this.Ea||this.sb()?0:1;this.Gb()}oc(e){e=!!e;this.V!==e&&(this.V=e,this.j&&(this.j.loop=e))}Ca(){let e=this.Z;this.Rc&&(e*=this.i.Wb);this.j&&(this.j.playbackRate.value=e)}nc(e){this.F||this.R()||(this.D?this.L=e:(this.Ra(),this.L=e,this.ub()))}hc(){return this.L}pc(e){e?
this.IsPlaying()?(this.ia=!0,this.L=this.ya(!0),this.V&&(this.L%=this.ea()),this.j.stop(0)):this.ia=!1:this.ia&&(T(this),this.j=this.W().createBufferSource(),this.j.buffer=this.J.aa,this.j.connect(this.K),this.Ta=this.j,this.j.onended=this.Rb,this.j.loop=this.V,this.Gb(),this.Ca(),this.Vb=this.qb()-this.L/(this.Z||.001),this.j.start(0,this.L),this.ia=!1)}xc(e){super.xc(e);this.L=e.resumePosition}};"use strict";
{class e{constructor(a){this.i=a;this.f=a.W();this.Pd=-1;this.O=this.$="";this.g=null}c(){this.f=null}fg(a){this.Pd=a}ng(a){this.$=a}o(){return this.f.createGain()}N(){}P(){}m(a,b,c,g){a.cancelScheduledValues(0);if(0===g)a.value=b;else{var l=this.f.currentTime;g+=l;switch(c){case 0:a.setValueAtTime(b,g);break;case 1:a.setValueAtTime(a.value,l);a.linearRampToValueAtTime(b,g);break;case 2:a.setValueAtTime(a.value,l),a.exponentialRampToValueAtTime(b,g)}}}Pa(){return{type:this.O,tag:this.$,params:this.g}}}
self.le=class extends e{constructor(a,b,c,g,l,t,d){super(a);this.O="filter";this.g=[b,c,g,l,t,d];this.l=this.o();this.b=this.o();this.b.gain.value=d;this.a=this.o();this.a.gain.value=1-d;this.u=this.f.createBiquadFilter();this.u.type=b;this.u.frequency.value=c;this.u.detune.value=g;this.u.Q.value=l;this.u.gain.vlaue=t;this.l.connect(this.u);this.l.connect(this.a);this.u.connect(this.b)}c(){this.l.disconnect();this.u.disconnect();this.b.disconnect();this.a.disconnect();super.c()}P(a){this.b.disconnect();
this.b.connect(a);this.a.disconnect();this.a.connect(a)}N(){return this.l}Y(a,b,c,g){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[5]=b;this.m(this.b.gain,b,c,g);this.m(this.a.gain,1-b,c,g);break;case 1:this.g[1]=b;this.m(this.u.frequency,b,c,g);break;case 2:this.g[2]=b;this.m(this.u.detune,b,c,g);break;case 3:this.g[3]=b;this.m(this.u.Q,b,c,g);break;case 4:this.g[4]=b,this.m(this.u.gain,b,c,g)}}};self.je=class extends e{constructor(a,b,c,g){super(a);this.O="delay";this.g=[b,c,g];this.l=
this.o();this.b=this.o();this.b.gain.value=g;this.a=this.o();this.a.gain.value=1-g;this.fb=this.o();this.S=this.f.createDelay(b);this.S.delayTime.value=b;this.Xa=this.o();this.Xa.gain.value=c;this.l.connect(this.fb);this.l.connect(this.a);this.fb.connect(this.b);this.fb.connect(this.S);this.S.connect(this.Xa);this.Xa.connect(this.fb)}c(){this.l.disconnect();this.b.disconnect();this.a.disconnect();this.fb.disconnect();this.S.disconnect();this.Xa.disconnect();super.c()}P(a){this.b.disconnect();this.b.connect(a);
this.a.disconnect();this.a.connect(a)}N(){return this.l}Y(a,b,c,g){const l=self.da.hd;switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[2]=b;this.m(this.b.gain,b,c,g);this.m(this.a.gain,1-b,c,g);break;case 4:this.g[1]=l(b);this.m(this.Xa.gain,l(b),c,g);break;case 5:this.g[0]=b,this.m(this.S.delayTime,b,c,g)}}};self.ie=class extends e{constructor(a,b,c,g){super(a);this.O="convolution";this.g=[c,g];this.Kd=this.Jd="";this.l=this.o();this.b=this.o();this.b.gain.value=g;this.a=this.o();this.a.gain.value=
1-g;this.Wa=this.f.createConvolver();this.Wa.normalize=c;this.Wa.buffer=b;this.l.connect(this.Wa);this.l.connect(this.a);this.Wa.connect(this.b)}c(){this.l.disconnect();this.Wa.disconnect();this.b.disconnect();this.a.disconnect();super.c()}P(a){this.b.disconnect();this.b.connect(a);this.a.disconnect();this.a.connect(a)}N(){return this.l}Y(a,b,c,g){switch(a){case 0:b=Math.max(Math.min(b/100,1),0),this.g[1]=b,this.m(this.b.gain,b,c,g),this.m(this.a.gain,1-b,c,g)}}bg(a,b){this.Jd=a;this.Kd=b}Pa(){const a=
super.Pa();a.bufferOriginalUrl=this.Jd;a.bufferUrl="";a.bufferType=this.Kd;return a}};self.me=class extends e{constructor(a,b,c,g,l,t){super(a);this.O="flanger";this.g=[b,c,g,l,t];this.l=this.o();this.a=this.o();this.a.gain.value=1-t/2;this.b=this.o();this.b.gain.value=t/2;this.Za=this.o();this.Za.gain.value=l;this.S=this.f.createDelay(b+c);this.S.delayTime.value=b;this.s=this.f.createOscillator();this.s.frequency.value=g;this.G=this.o();this.G.gain.value=c;this.l.connect(this.S);this.l.connect(this.a);
this.S.connect(this.b);this.S.connect(this.Za);this.Za.connect(this.S);this.s.connect(this.G);this.G.connect(this.S.delayTime);this.s.start(0)}c(){this.s.stop(0);this.l.disconnect();this.S.disconnect();this.s.disconnect();this.G.disconnect();this.a.disconnect();this.b.disconnect();this.Za.disconnect();super.c()}P(a){this.b.disconnect();this.b.connect(a);this.a.disconnect();this.a.connect(a)}N(){return this.l}Y(a,b,c,g){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[4]=b;this.m(this.b.gain,
b/2,c,g);this.m(this.a.gain,1-b/2,c,g);break;case 6:this.g[1]=b/1E3;this.m(this.G.gain,b/1E3,c,g);break;case 7:this.g[2]=b;this.m(this.s.frequency,b,c,g);break;case 8:this.g[3]=b/100,this.m(this.Za.gain,b/100,c,g)}}};self.oe=class extends e{constructor(a,b,c,g,l,t,d){super(a);this.O="phaser";this.g=[b,c,g,l,t,d];this.l=this.o();this.a=this.o();this.a.gain.value=1-d/2;this.b=this.o();this.b.gain.value=d/2;this.u=this.f.createBiquadFilter();this.u.type="allpass";this.u.frequency.value=b;this.u.detune.value=
c;this.u.Q.value=g;this.s=this.f.createOscillator();this.s.frequency.value=t;this.G=this.o();this.G.gain.value=l;this.l.connect(this.u);this.l.connect(this.a);this.u.connect(this.b);this.s.connect(this.G);this.G.connect(this.u.frequency);this.s.start(0)}c(){this.s.stop(0);this.l.disconnect();this.u.disconnect();this.s.disconnect();this.G.disconnect();this.a.disconnect();this.b.disconnect();super.c()}P(a){this.b.disconnect();this.b.connect(a);this.a.disconnect();this.a.connect(a)}N(){return this.l}Y(a,
b,c,g){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[5]=b;this.m(this.b.gain,b/2,c,g);this.m(this.a.gain,1-b/2,c,g);break;case 1:this.g[0]=b;this.m(this.u.frequency,b,c,g);break;case 2:this.g[1]=b;this.m(this.u.detune,b,c,g);break;case 3:this.g[2]=b;this.m(this.u.Q,b,c,g);break;case 6:this.g[3]=b;this.m(this.G.gain,b,c,g);break;case 7:this.g[4]=b,this.m(this.s.frequency,b,c,g)}}};self.ne=class extends e{constructor(a,b){super(a);this.O="gain";this.g=[b];this.h=this.o();this.h.gain.value=
b}c(){this.h.disconnect();super.c()}P(a){this.h.disconnect();this.h.connect(a)}N(){return this.h}Y(a,b,c,g){const l=self.da.hd;switch(a){case 4:this.g[0]=l(b),this.m(this.h.gain,l(b),c,g)}}};self.qe=class extends e{constructor(a,b,c){super(a);this.O="tremolo";this.g=[b,c];this.h=this.o();this.h.gain.value=1-c/2;this.s=this.f.createOscillator();this.s.frequency.value=b;this.G=this.o();this.G.gain.value=c/2;this.s.connect(this.G);this.G.connect(this.h.gain);this.s.start(0)}c(){this.s.stop(0);this.s.disconnect();
this.G.disconnect();this.h.disconnect();super.c()}P(a){this.h.disconnect();this.h.connect(a)}N(){return this.h}Y(a,b,c,g){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[1]=b;this.m(this.h.gain.value,1-b/2,c,g);this.m(this.G.gain.value,b/2,c,g);break;case 7:this.g[0]=b,this.m(this.s.frequency,b,c,g)}}};self.pe=class extends e{constructor(a,b,c){super(a);this.O="ringmod";this.g=[b,c];this.l=this.o();this.b=this.o();this.b.gain.value=c;this.a=this.o();this.a.gain.value=1-c;this.lb=this.o();
this.lb.gain.value=0;this.s=this.f.createOscillator();this.s.frequency.value=b;this.s.connect(this.lb.gain);this.s.start(0);this.l.connect(this.lb);this.l.connect(this.a);this.lb.connect(this.b)}c(){this.s.stop(0);this.s.disconnect();this.lb.disconnect();this.l.disconnect();this.b.disconnect();this.a.disconnect();super.c()}P(a){this.b.disconnect();this.b.connect(a);this.a.disconnect();this.a.connect(a)}N(){return this.l}Y(a,b,c,g){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[1]=b;this.m(this.b.gain,
b,c,g);this.m(this.a.gain,1-b,c,g);break;case 7:this.g[0]=b,this.m(this.s.frequency,b,c,g)}}};self.ke=class extends e{constructor(a,b,c,g,l,t){super(a);this.O="distortion";this.g=[b,c,g,l,t];this.l=this.o();this.Tb=this.o();this.Sb=this.o();this.cg(g,l);this.b=this.o();this.b.gain.value=t;this.a=this.o();this.a.gain.value=1-t;this.Xb=this.f.createWaveShaper();this.Kc=new Float32Array(65536);this.kf(b,c);this.Xb.curve=this.Kc;this.l.connect(this.Tb);this.l.connect(this.a);this.Tb.connect(this.Xb);
this.Xb.connect(this.Sb);this.Sb.connect(this.b)}c(){this.l.disconnect();this.Tb.disconnect();this.Xb.disconnect();this.Sb.disconnect();this.b.disconnect();this.a.disconnect();super.c()}cg(a,b){.01>a&&(a=.01);this.Tb.gain.value=a;this.Sb.gain.value=Math.pow(1/a,.6)*b}kf(a,b){for(let c=0;32768>c;++c){let g=c/32768;g=this.pg(g,a,b);this.Kc[32768+c]=g;this.Kc[32768-c-1]=-g}}pg(a,b,c){c=1.05*c*b-b;const g=0>a?-a:a;return(g<b?g:b+c*self.da.Hg(g-b,1/c))*(0>a?-1:1)}P(a){this.b.disconnect();this.b.connect(a);
this.a.disconnect();this.a.connect(a)}N(){return this.l}Y(a,b,c,g){switch(a){case 0:b=Math.max(Math.min(b/100,1),0),this.g[4]=b,this.m(this.b.gain,b,c,g),this.m(this.a.gain,1-b,c,g)}}};self.he=class extends e{constructor(a,b,c,g,l,t){super(a);this.O="compressor";this.g=[b,c,g,l,t];this.h=this.f.createDynamicsCompressor();this.h.threshold.value=b;this.h.knee.value=c;this.h.ratio.value=g;this.h.attack.value=l;this.h.release.value=t}c(){this.h.disconnect();super.c()}P(a){this.h.disconnect();this.h.connect(a)}N(){return this.h}Y(){}};
self.ge=class extends e{constructor(a,b,c){super(a);this.O="analyser";this.g=[b,c];this.h=this.f.createAnalyser();this.h.fftSize=b;this.h.smoothingTimeConstant=c;this.Nd=new Float32Array(this.h.frequencyBinCount);this.$d=new Uint8Array(b);this.Yd=this.Ha=0;this.i.Ue(this)}c(){this.i.Vf(this);this.h.disconnect();super.c()}qa(){this.h.getFloatFrequencyData(this.Nd);this.h.getByteTimeDomainData(this.$d);const a=this.h.fftSize;let b=this.Ha=0;for(var c=0;c<a;++c){let g=(this.$d[c]-128)/128;0>g&&(g=-g);
this.Ha<g&&(this.Ha=g);b+=g*g}c=self.da.Je;this.Ha=c(this.Ha);this.Yd=c(Math.sqrt(b/a))}P(a){this.h.disconnect();this.h.connect(a)}N(){return this.h}Y(){}Ae(){return{tag:this.$,index:this.Pd,peak:this.Ha,rms:this.Yd,binCount:this.h.frequencyBinCount,freqBins:this.Nd}}}}"use strict";
async function ia(){const e=[],a=[];if(navigator.mediaDevices&&navigator.mediaDevices.enumerateDevices){var b=await navigator.mediaDevices.enumerateDevices();for(const c of b){b=c.kind;const g={deviceId:c.deviceId,label:c.label,facing:c.facing||c.facingMode||""};"video"===b||"videoinput"===b?e.push(g):("audio"===b||"audioinput"===b)&&a.push(g)}}return{videoSources:e,audioSources:a}}
async function ja(e,a,b){try{const c=e.v;"object"===typeof b.constraints.audio?await c.mc("CAMERA","RECORD_AUDIO","MODIFY_AUDIO_SETTINGS"):await c.mc("CAMERA");e.ua=await navigator.mediaDevices.getUserMedia(b.constraints);a.srcObject=e.ua;a.play();e.Rd&&C(e);return{ok:!0}}catch(c){return console.warn("Error requesting camera: ",c),{ok:!1}}}
async function ka(e,a){try{return await e.v.mc("RECORD_AUDIO","MODIFY_AUDIO_SETTINGS"),e.ua=await navigator.mediaDevices.getUserMedia(a.constraints),self.C3Audio_OnMicrophoneStream&&self.C3Audio_OnMicrophoneStream(e.ua,a.tag),{ok:!0}}catch(b){return console.warn("Error requesting microphone: ",b),{ok:!1}}}
async function la(e,a){const b=document.createElement("canvas");b.width=e.videoWidth;b.height=e.videoHeight;b.getContext("2d").drawImage(e,0,0,e.videoWidth,e.videoHeight);return{snapshotUrl:await ma(b,a.format,a.quality)}}function U(e,a){e.ua===a&&(e.ua=null);e=a.getTracks();for(let b=0,c=e.length;b<c;++b)e[b].stop()}function ma(e,a,b){return new Promise(c=>{e.toBlob?e.toBlob(g=>c(URL.createObjectURL(g)),a,b):c(e.toDataURL(a,b))})}
self.Aa.Oa(class extends self.ac{constructor(e){super(e,"user-media");this.Ua=!1;this.Rd=this.v.xa;this.Eg=0;this.ua=null;A(this,"get-media-sources",()=>ia());G(this,"request-camera",(a,b)=>ja(this,a,b));G(this,"request-microphone",(a,b)=>ka(this,b));G(this,"snapshot",(a,b)=>la(a,b));G(this,"stop",a=>this.Hc(a));self.C3UserMedia_GetVideoElement=a=>this.T.get(a);self.C3UserMedia_GetLastMediaStream=()=>this.ua}pb(e){const a=document.createElement("video");a.crossOrigin="anonymous";a.autoplay=!0;a.muted=
!0;a.playsInline=!0;a.addEventListener("canplaythrough",()=>{F(this,"video-ready",e,{width:a.videoWidth,height:a.videoHeight})});return a}Ba(){}jd(e){e.srcObject&&(U(this,e.srcObject),e.srcObject=null)}Hc(e){e.srcObject&&(U(this,e.srcObject),e.srcObject=null)}qa(){if(this.Rd){var e={},a={sequenceNumber:this.Eg++,videoData:e},b=[],c=[];for(const [g,l]of this.T.entries()){if(!l.srcObject)continue;const t={};c.push(createImageBitmap(l).then(d=>{t.imageBitmap=d;b.push(d)}).catch(()=>{t.imageBitmap=null}));
e[g.toString()]=t}Promise.all(c).then(()=>v(this,"state",a,!1,b))}}});"use strict";function V(e){e.stopPropagation()}function W(e){const a=document.createElement("option");a.text=e;return a}function X(e){const a=e.selectedIndex,b=[];for(let c=0,g=e.length;c<g;++c)e.options[c].selected&&b.push(c);return{selectedIndex:a,selectedIndices:b}}
self.Aa.Oa(class extends self.ac{constructor(e){super(e,"list");G(this,"set-selected-index",(a,b)=>{a.selectedIndex=b.selectedIndex});G(this,"add-item",(a,b)=>{{const c=b.index;b=W(b.text);0>c?a.add(b):a.add(b,c)}});G(this,"remove-item",(a,b)=>{a.remove(b.index)});G(this,"set-item",(a,b)=>{a.options[b.index].text=b.text});G(this,"clear",a=>{a.innerHTML=""});G(this,"load-state",(a,b)=>this.Bc(a,b))}pb(e,a){const b=a.isDropdown,c=a.isMultiSelect,g=a.items,l=document.createElement("select");l.style.position=
"absolute";l.style.userSelect="none";l.style.webkitUserSelect="none";l.multiple=c;b||(l.size=2);for(const t of g)l.add(W(t));l.addEventListener("touchstart",V);l.addEventListener("touchmove",V);l.addEventListener("touchend",V);l.addEventListener("mousedown",V);l.addEventListener("mouseup",V);l.addEventListener("click",t=>{t.stopPropagation();H(this,"click",e,X(l))});l.addEventListener("dblclick",t=>{t.stopPropagation();H(this,"dblclick",e,X(l))});l.addEventListener("change",()=>F(this,"change",e,
X(l)));a.id&&(l.id=a.id);this.Ba(l,a);return l}Ba(e,a){e.title=a.title;e.disabled=!a.isEnabled;e.multiple=!!a.isMultiSelect}Bc(e,a){e.innerHTML="";for(const b of a.items)e.add(W(b));e.selectedIndex=a.selectedIndex;for(const b of a.selectedIndices)if(a=e.options[b])a.selected=!0}});"use strict";function Z(e){e.stopPropagation()}
self.Aa.Oa(class extends self.ac{constructor(e){super(e,"button")}pb(e,a){const b=document.createElement("input");var c=b;a.isCheckbox?(b.type="checkbox",c=document.createElement("label"),c.appendChild(b),c.appendChild(document.createTextNode("")),c.style.fontFamily="sans-serif",c.style.userSelect="none",c.style.webkitUserSelect="none",c.style.display="inline-block",c.style.color="black"):b.type="button";c.style.position="absolute";c.addEventListener("touchstart",Z);c.addEventListener("touchmove",
Z);c.addEventListener("touchend",Z);c.addEventListener("mousedown",Z);c.addEventListener("mouseup",Z);c.addEventListener("keydown",Z);c.addEventListener("keyup",Z);b.addEventListener("click",()=>H(this,"click",e,{isChecked:b.checked}));a.id&&(b.id=a.id);this.Ba(c,a);return c}Ba(e,a){const b="input"===e.tagName.toLowerCase()?e:e.firstChild;b.checked=a.isChecked;b.disabled=!a.isEnabled;e.title=a.title;e===b?b.value=a.text:e.lastChild.textContent=a.text}});