'use strict';function v(d,a,b,c,g){d.v.kc(d.Wa,a,b,c,g)}function x(d,a,b,c){d.v.Aa?v(d,a,b,c):d.v.lf()._OnMessageFromDOM({type:"event",component:d.Wa,handler:a,dispatchOpts:c||null,data:b,responseId:null})}function A(d,a,b){d.v.B(d.Wa,a,b)}function B(d,a){for(const [b,c]of a)A(d,b,c)}function C(d){d.Ob||(d.v.We(d.be),d.Ob=!0)}window.rb=class{constructor(d,a){this.v=d;this.Wa=a;this.Ob=!1;this.be=()=>this.ta()}dd(){}ta(){}};function D(d){-1!==d.Na&&(self.clearTimeout(d.Na),d.Na=-1)}
window.Me=class{constructor(d,a){this.Jc=d;this.yg=a;this.Na=-1;this.Pb=-Infinity;this.ce=()=>{this.Na=-1;this.Pb=Date.now();this.ab=!0;this.Jc();this.ab=!1};this.Ld=this.ab=!1}c(){D(this);this.ce=this.Jc=null}};"use strict";function E(d,a){const b=a.elementId,c=d.Pa(b,a);d.T.set(b,c);a.isVisible||(c.style.display="none");c.addEventListener("focus",()=>{F(d,"elem-focused",b)});c.addEventListener("blur",()=>{F(d,"elem-blurred",b)});d.Va&&document.body.appendChild(c)}
function G(d,a,b){A(d,a,c=>{const g=d.T.get(c.elementId);return b(g,c)})}function F(d,a,b,c){c||(c={});c.elementId=b;v(d,a,c)}function H(d,a,b,c){c||(c={});c.elementId=b;x(d,a,c)}
window.qb=class extends self.rb{constructor(d,a){super(d,a);this.T=new Map;this.Va=!0;B(this,[["create",b=>E(this,b)],["destroy",b=>{{b=b.elementId;const c=this.T.get(b);this.jd(c);this.Va&&c.parentElement.removeChild(c);this.T.delete(b)}}],["set-visible",b=>{this.Va&&(this.T.get(b.elementId).style.display=b.isVisible?"":"none")}],["update-position",b=>{if(this.Va){var c=this.T.get(b.elementId);c.style.left=b.left+"px";c.style.top=b.top+"px";c.style.width=b.width+"px";c.style.height=b.height+"px";
b=b.fontSize;null!==b&&(c.style.fontSize=b+"em")}}],["update-state",b=>{{const c=this.T.get(b.elementId);this.ma(c,b)}}],["focus",b=>{{const c=this.T.get(b.elementId);b.focus?c.focus():c.blur()}}],["set-css-style",b=>{this.T.get(b.elementId).style[b.prop]=b.val}],["set-attribute",b=>{this.T.get(b.elementId).setAttribute(b.name,b.val)}],["remove-attribute",b=>{this.T.get(b.elementId).removeAttribute(b.name)}]]);G(this,"get-element",b=>b)}Pa(){throw Error("required override");}jd(){}ma(){throw Error("required override");
}};"use strict";
{var I=function(q){return m.has(q)},J=function(q){return new Promise((f,k)=>{const n=new FileReader;n.onload=r=>f(r.target.result);n.onerror=r=>k(r);n.readAsArrayBuffer(q)})},K=async function(q){q=await J(q);return(new TextDecoder("utf-8")).decode(q)},L=function(q){if(q.Jg){const f=document.createElement("script");f.async=!1;f.textContent=q.Mg;document.head.appendChild(f)}else return new Promise((f,k)=>{const n=document.createElement("script");n.onload=f;n.onerror=k;n.async=!1;n.src=q;document.head.appendChild(n)})};
const d=/(iphone|ipod|ipad|macos|macintosh|mac os x)/i.test(navigator.userAgent);let a=new Audio;const b={"audio/webm; codecs=opus":!!a.canPlayType("audio/webm; codecs=opus"),"audio/ogg; codecs=opus":!!a.canPlayType("audio/ogg; codecs=opus"),"audio/webm; codecs=vorbis":!!a.canPlayType("audio/webm; codecs=vorbis"),"audio/ogg; codecs=vorbis":!!a.canPlayType("audio/ogg; codecs=vorbis"),"audio/mp4":!!a.canPlayType("audio/mp4"),"audio/mpeg":!!a.canPlayType("audio/mpeg")};a=null;const c=[];let g=0;window.RealFile=
window.File;const l=[],t=new Map,e=new Map;let h=0;const p=[];self.Wg=function(q){if("function"!==typeof q)throw Error("runOnStartup called without a function");p.push(q)};const m=new Set(["cordova","playable-ad","instant-games"]);window.ka=class q{constructor(f){this.Aa=f.Og;this.oa=null;this.X="";this.Yc=f.Lg;this.pb={};this.Ga=this.ob=null;this.Mb=[];this.cb=this.I=this.La=null;this.Ka=-1;this.Dg=()=>this.Jf();this.Ja=[];this.U=f.de;I(this.U)&&this.Aa&&(console.warn("[C3 runtime] Worker mode is enabled and supported, but is disabled in WebViews due to crbug.com/923007. Reverting to DOM mode."),
this.Aa=!1);this.ad=!1;this.Rb=this.ha=null;"html5"!==this.U&&"playable-ad"!==this.U||"file"!==location.protocol.substr(0,4)||alert("Exported games won't work until you upload them. (When running on the file: protocol, browsers block many features from working for security reasons.)");this.B("runtime","cordova-fetch-local-file",k=>this.vf(k));this.B("runtime","create-job-worker",()=>this.wf());"cordova"===this.U?document.addEventListener("deviceready",()=>this.yd(f)):this.yd(f)}c(){this.rc();this.oa&&
(this.oa=this.oa.onmessage=null);this.ob&&(this.ob.terminate(),this.ob=null);this.Ga&&(this.Ga.c(),this.Ga=null);this.I&&(this.I.parentElement.removeChild(this.I),this.I=null)}jc(){return d&&"cordova"===this.U}vb(){return d&&I(this.U)||navigator.standalone}async yd(f){if("playable-ad"===this.U){this.ha=self.c3_base64files;this.Rb={};await this.af();for(let n=0,r=f.Oa.length;n<r;++n){var k=f.Oa[n].toLowerCase();this.Rb.hasOwnProperty(k)?f.Oa[n]={Jg:!0,Mg:this.Rb[k]}:this.ha.hasOwnProperty(k)&&(f.Oa[n]=
URL.createObjectURL(this.ha[k]))}}f.Gg?this.X=f.Gg:(k=location.origin,this.X=("null"===k?"file:///":k)+location.pathname,k=this.X.lastIndexOf("/"),-1!==k&&(this.X=this.X.substr(0,k+1)));if(f.Qg)for(const [n,r]of Object.entries(f.Qg))this.pb[n]=URL.createObjectURL(r);k=new MessageChannel;this.oa=k.port1;this.oa.onmessage=n=>this._OnMessageFromRuntime(n.data);window.c3_addPortMessageHandler&&window.c3_addPortMessageHandler(n=>this.Ff(n));this.cb=new self.Ie(this);await this.cb.Ee();this.md();"object"===
typeof window.StatusBar&&window.StatusBar.hide();"object"===typeof window.AndroidFullScreen&&window.AndroidFullScreen.immersiveMode();await this.rg();this.Aa?await this.pf(f,k.port2):await this.nf(f,k.port2)}uc(f){return this.pb.hasOwnProperty(f)?this.pb[f]:f.endsWith("/workermain.js")&&this.pb.hasOwnProperty("workermain.js")?this.pb["workermain.js"]:"playable-ad"===this.U&&this.ha.hasOwnProperty(f.toLowerCase())?URL.createObjectURL(this.ha[f.toLowerCase()]):f}async bc(f,k,n){if(f.startsWith("blob:"))return new Worker(f,
n);if(this.jc()&&"file:"===location.protocol)return f=await this.ac(this.Yc+f),new Worker(URL.createObjectURL(new Blob([f],{type:"application/javascript"})),n);f=new URL(f,k);if(location.origin!==f.origin){f=await fetch(f);if(!f.ok)throw Error("failed to fetch worker script");f=await f.blob();return new Worker(URL.createObjectURL(f),n)}return new Worker(f,n)}md(){if(this.vb()){const f=document.documentElement.style,k=document.body.style,n=window.innerWidth<window.innerHeight,r=n?window.screen.width:
window.screen.height;k.height=f.height=(n?window.screen.height:window.screen.width)+"px";k.width=f.width=r+"px"}}wd(f){return{baseUrl:this.X,windowInnerWidth:window.innerWidth,windowInnerHeight:window.innerHeight,devicePixelRatio:window.devicePixelRatio,isFullscreen:q.ic(),projectData:f.Vg,previewImageBlobs:window.cr_previewImageBlobs||this.ha,previewProjectFileBlobs:window.cr_previewProjectFileBlobs,exportType:f.de,isDebug:-1<self.location.search.indexOf("debug"),ife:!!self.Ug,jobScheduler:this.cb.Ce(),
supportedAudioFormats:b,opusWasmScriptUrl:window.cr_opusWasmScriptUrl||this.Yc+"opus.wasm.js",opusWasmBinaryUrl:window.cr_opusWasmBinaryUrl||this.Yc+"opus.wasm.wasm",isiOSCordova:this.jc(),isiOSWebView:this.vb(),isFBInstantAvailable:"undefined"!==typeof self.FBInstant}}async pf(f,k){var n=this.uc(f.Pg);this.ob=await this.bc(n,this.X,{name:"Runtime"});this.I=document.createElement("canvas");this.I.style.display="none";n=this.I.transferControlToOffscreen();document.body.appendChild(this.I);window.c3canvas=
this.I;this.ob.postMessage(Object.assign(this.wd(f),{type:"init-runtime",isInWorker:!0,messagePort:k,canvas:n,workerDependencyScripts:f.cd||[],engineScripts:f.Oa,projectScripts:window.Tg,projectScriptsStatus:self.C3_ProjectScriptsStatus}),[k,n,...this.cb.De()]);this.Mb=l.map(r=>new r(this));this.vd();self.c3_callFunction=(r,u)=>this.La.qf(r,u);"preview"===this.U&&(self.goToLastErrorScript=()=>this.kc("runtime","go-to-last-error-script"))}async nf(f,k){this.I=document.createElement("canvas");this.I.style.display=
"none";document.body.appendChild(this.I);window.c3canvas=this.I;this.Mb=l.map(r=>new r(this));this.vd();const n=f.Oa.map(r=>"string"===typeof r?(new URL(r,this.X)).toString():r);Array.isArray(f.cd)&&n.unshift(...f.cd);await Promise.all(n.map(r=>L(r)));if(f.ee&&0<f.ee.length){const r=self.C3_ProjectScriptsStatus;try{if(await Promise.all(f.ee.map(u=>L(u[1]))),Object.values(r).some(u=>!u)){self.setTimeout(()=>this.Gd(r),100);return}}catch(u){console.error("[Preview] Error loading project scripts: ",
u);self.setTimeout(()=>this.Gd(r),100);return}}"preview"===this.U&&"object"!==typeof self.Rg.Sg?(console.error("[C3 runtime] Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax."),alert("Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax.")):(f=Object.assign(this.wd(f),{isInWorker:!1,messagePort:k,canvas:this.I,runOnStartupFunctions:p}),this.Ga=self.C3_CreateRuntime(f),await self.C3_InitRuntime(this.Ga,f))}Gd(f){f=
`Failed to load project script '${Object.entries(f).filter(k=>!k[1]).map(k=>k[0])[0]}'. Check all your JavaScript code has valid syntax.`;console.error("[Preview] "+f);alert(f)}async wf(){const f=await this.cb.ud();return{outputPort:f,transferables:[f]}}lf(){if(this.Aa)throw Error("not available in worker mode");return this.Ga}kc(f,k,n,r,u){this.oa.postMessage({type:"event",component:f,handler:k,dispatchOpts:r||null,data:n,responseId:null},this.ad?void 0:u)}nd(f,k,n,r,u){const y=h++,w=new Promise((z,
aa)=>{e.set(y,{resolve:z,reject:aa})});this.oa.postMessage({type:"event",component:f,handler:k,dispatchOpts:r||null,data:n,responseId:y},this.ad?void 0:u);return w}["_OnMessageFromRuntime"](f){const k=f.type;if("event"===k)return this.Bf(f);if("result"===k)this.Mf(f);else if("runtime-ready"===k)this.Nf();else if("alert"===k)alert(f.message);else throw Error(`unknown message '${k}'`);}Bf(f){const k=f.component,n=f.handler,r=f.data,u=f.responseId;if(f=t.get(k))if(f=f.get(n)){var y=null;try{y=f(r)}catch(w){console.error(`Exception in '${k}' handler '${n}':`,
w);null!==u&&this.Fb(u,!1,""+w);return}if(null===u)return y;y&&y.then?y.then(w=>this.Fb(u,!0,w)).catch(w=>{console.error(`Rejection from '${k}' handler '${n}':`,w);this.Fb(u,!1,""+w)}):this.Fb(u,!0,y)}else console.warn(`[DOM] No handler '${n}' for component '${k}'`);else console.warn(`[DOM] No event handlers for component '${k}'`)}Fb(f,k,n){let r;n&&n.transferables&&(r=n.transferables);this.oa.postMessage({type:"result",responseId:f,isOk:k,result:n},r)}Mf(f){const k=f.responseId,n=f.isOk;f=f.result;
const r=e.get(k);n?r.resolve(f):r.reject(f);e.delete(k)}B(f,k,n){let r=t.get(f);r||(r=new Map,t.set(f,r));if(r.has(k))throw Error(`[DOM] Component '${f}' already has handler '${k}'`);r.set(k,n)}static qa(f){if(l.includes(f))throw Error("DOM handler already added");l.push(f)}vd(){for(const f of this.Mb)if("runtime"===f.Wa){this.La=f;return}throw Error("cannot find runtime DOM handler");}Ff(f){this.kc("debugger","message",f)}Nf(){for(const f of this.Mb)f.dd()}static ic(){return!!(document.fullscreenElement||
document.webkitFullscreenElement||document.mozFullScreenElement)}We(f){this.Ja.push(f);this.Gc()}Yf(f){f=this.Ja.indexOf(f);if(-1===f)throw Error("invalid callback");this.Ja.splice(f,1);this.Ja.length||this.rc()}Gc(){-1===this.Ka&&this.Ja.length&&(this.Ka=requestAnimationFrame(this.Dg))}rc(){-1!==this.Ka&&(cancelAnimationFrame(this.Ka),this.Ka=-1)}Jf(){this.Ka=-1;for(const f of this.Ja)f();this.Gc()}ua(f){this.La.ua(f)}Ca(f){this.La.Ca(f)}Fc(){this.La.Fc()}yb(f){this.La.yb(f)}Ge(){return!!b["audio/webm; codecs=opus"]}async wg(f){f=
await this.nd("runtime","opus-decode",{arrayBuffer:f},null,[f]);return new Float32Array(f)}Fe(f){return/^(?:[a-z]+:)?\/\//.test(f)||"data:"===f.substr(0,5)||"blob:"===f.substr(0,5)}He(f){return!this.Fe(f)}async vf(f){const k=f.filename;switch(f.as){case "text":return await this.ve(k);case "buffer":return await this.ac(k);default:throw Error("unsupported type");}}xd(){const f=window.cordova&&window.cordova.plugins&&window.cordova.plugins.permissions;if("object"!==typeof f)throw Error("Permission API is not loaded");
return f}Ad(f,k){f=f[k];if("string"!==typeof f)throw Error("Invalid permission name");return f}mf(f){const k=this.xd();return new Promise((n,r)=>k.checkPermission(this.Ad(k,f),u=>n(!!u.hasPermission),r))}Zf(f){const k=this.xd();return new Promise((n,r)=>k.requestPermission(this.Ad(k,f),u=>n(!!u.hasPermission),r))}async Pe(f){if("cordova"!==this.U||this.jc())return!0;for(const k of f)if(!await this.mf(k)&&!1===await this.Zf(k))return!1;return!0}async mc(...f){if(!1===await this.Pe(f))throw Error("Permission not granted");
}gd(f){const k=window.cordova.file.applicationDirectory+"www/"+f.toLowerCase();return new Promise((n,r)=>{window.resolveLocalFileSystemURL(k,u=>{u.file(n,r)},r)})}async ve(f){f=await this.gd(f);return await K(f)}sc(){if(c.length&&!(8<=g)){g++;var f=c.shift();this.bf(f.filename,f.Ng,f.Ig)}}ac(f){return new Promise((k,n)=>{c.push({filename:f,Ng:r=>{g--;this.sc();k(r)},Ig:r=>{g--;this.sc();n(r)}});this.sc()})}async bf(f,k,n){try{const r=await this.gd(f),u=await J(r);k(u)}catch(r){n(r)}}async af(){const f=
[];for(const [k,n]of Object.entries(this.ha))f.push(this.$e(k,n));await Promise.all(f)}async $e(f,k){if("object"===typeof k)this.ha[f]=new Blob([k.str],{type:k.type}),this.Rb[f]=k.str;else{let n=await this.jf(k);n||(n=this.df(k));this.ha[f]=n}}async jf(f){try{return await (await fetch(f)).blob()}catch(k){return console.warn("Failed to fetch a data: URI. Falling back to a slower workaround. This is probably because the Content Security Policy unnecessarily blocked it. Allow data: URIs in your CSP to avoid this.",
k),null}}df(f){f=this.Sf(f);return this.Ze(f.data,f.Kg)}Sf(f){var k=f.indexOf(",");if(0>k)throw new URIError("expected comma in data: uri");var n=f.substring(k+1);k=f.substring(5,k).split(";");f=k[0]||"";const r=k[2];n="base64"===k[1]||"base64"===r?atob(n):decodeURIComponent(n);return{Kg:f,data:n}}Ze(f,k){var n=f.length;let r=n>>2,u=new Uint8Array(n),y=new Uint32Array(u.buffer,0,r),w,z;for(z=w=0;w<r;++w)y[w]=f.charCodeAt(z++)|f.charCodeAt(z++)<<8|f.charCodeAt(z++)<<16|f.charCodeAt(z++)<<24;for(n&=
3;n--;)u[z]=f.charCodeAt(z),++z;return new Blob([u],{type:k})}rg(){let f=null;const k=new Promise(u=>f=u),n=new ArrayBuffer(1),r=new MessageChannel;r.port2.onmessage=u=>{u.data&&u.data.arrayBuffer||(this.ad=!0,console.warn("MessageChannel transfers determined to be broken. Disabling transferables."));f()};r.port1.postMessage({arrayBuffer:n},[n]);return k}}}"use strict";
{var ba=function(){const e=document.activeElement;if(!e)return!1;const h=e.tagName.toLowerCase(),p=new Set("email number password search tel text url".split(" "));return"textarea"===h?!0:"input"===h?p.has(e.type.toLowerCase()||"text"):M(e)},ca=function(){try{return window.parent&&window.parent.document.hasFocus()}catch(e){return!1}},N=function(e){(e.metaKey||e.ctrlKey)&&e.preventDefault()},O=function(e){l.has(e.target.tagName.toLowerCase())&&e.preventDefault()},M=function(e){do{if(e.parentNode&&e.hasAttribute("contenteditable"))return!0;
e=e.parentNode}while(e);return!1},ea=async function(e,h,p){if(!/firefox/i.test(navigator.userAgent))return await P(e);var m=await da(e);m=(new DOMParser).parseFromString(m,"image/svg+xml");const q=m.documentElement;if(q.hasAttribute("width")&&q.hasAttribute("height")){const f=q.getAttribute("width"),k=q.getAttribute("height");if(!f.includes("%")&&!k.includes("%"))return await P(e)}q.setAttribute("width",h+"px");q.setAttribute("height",p+"px");m=(new XMLSerializer).serializeToString(m);e=new Blob([m],
{type:"image/svg+xml"});return await P(e)},da=function(e){return new Promise((h,p)=>{let m=new FileReader;m.onload=q=>h(q.target.result);m.onerror=q=>p(q);m.readAsText(e)})},P=async function(e){e=URL.createObjectURL(e);try{return await fa(e)}finally{URL.revokeObjectURL(e)}},fa=function(e){return new Promise((h,p)=>{const m=new Image;m.onload=()=>h(m);m.onerror=q=>p(q);m.src=e})},ha=function(e){return new Promise((h,p)=>{const m=document.createElement("link");m.onload=()=>h(m);m.onerror=q=>p(q);m.rel=
"stylesheet";m.href=e;document.head.appendChild(m)})},Q=function(e){return e.sourceCapabilities&&e.sourceCapabilities.firesTouchEvents||e.originalEvent&&e.originalEvent.sourceCapabilities&&e.originalEvent.sourceCapabilities.firesTouchEvents};const d=self.ka,a=new Map([["OSLeft","MetaLeft"],["OSRight","MetaRight"]]),b={dispatchRuntimeEvent:!0,dispatchUserScriptEvent:!0},c={dispatchUserScriptEvent:!0},g={dispatchRuntimeEvent:!0},l=new Set(["canvas","body","html"]);self.C3_GetSvgImageSize=async function(e){e=
await P(e);if(0<e.width&&0<e.height)return[e.width,e.height];{e.style.position="absolute";e.style.left="0px";e.style.top="0px";e.style.visibility="hidden";document.body.appendChild(e);const h=e.getBoundingClientRect();document.body.removeChild(e);return[h.width,h.height]}};self.C3_RasterSvgImageBlob=async function(e,h,p,m,q){e=await ea(e,h,p);const f=document.createElement("canvas");f.width=m;f.height=q;f.getContext("2d").drawImage(e,0,0,h,p);return f};let t=!1;document.addEventListener("pause",()=>
t=!0);document.addEventListener("resume",()=>t=!1);d.qa(class extends self.rb{constructor(e){super(e,"runtime");this.Qd=!0;this.Ma=-1;this.Zc="any";this.Hd=this.Id=!1;this.Sc=this.lb=this.wa=null;e.B("canvas","update-size",m=>this.Qf(m));e.B("runtime","invoke-download",m=>this.Ef(m));e.B("runtime","raster-svg-image",m=>this.Kf(m));e.B("runtime","get-svg-image-size",m=>this.Df(m));e.B("runtime","set-target-orientation",m=>this.Of(m));e.B("runtime","register-sw",()=>this.Lf());e.B("runtime","post-to-debugger",
m=>this.Cd(m));e.B("runtime","go-to-script",m=>this.Cd(m));e.B("runtime","before-start-ticking",()=>this.uf());e.B("runtime","debug-highlight",m=>this.xf(m));e.B("runtime","enable-device-orientation",()=>this.Ye());e.B("runtime","enable-device-motion",()=>this.Xe());e.B("runtime","add-stylesheet",m=>this.sf(m));e.B("runtime","alert",m=>this.tf(m));const h=new Set(["input","textarea","datalist"]);window.addEventListener("contextmenu",m=>{const q=m.target;h.has(q.tagName.toLowerCase())||M(q)||m.preventDefault()});
const p=e.I;window.addEventListener("selectstart",O);window.addEventListener("gesturehold",O);p.addEventListener("selectstart",O);p.addEventListener("gesturehold",O);window.addEventListener("touchstart",O,{passive:!1});"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",O,{passive:!1}),p.addEventListener("pointerdown",O)):p.addEventListener("touchstart",O);this.ib=0;window.addEventListener("mousedown",m=>{1===m.button&&m.preventDefault()});window.addEventListener("mousewheel",
N,{passive:!1});window.addEventListener("wheel",N,{passive:!1});window.addEventListener("resize",()=>this.Rf());e.vb()&&window.addEventListener("focusout",()=>{ba()||(document.scrollingElement.scrollTop=0)});this.Ha=new Set;this.Sb=new WeakSet;this.na=!1}uf(){"cordova"===this.v.U?(document.addEventListener("pause",()=>this.Ec(!0)),document.addEventListener("resume",()=>this.Ec(!1))):document.addEventListener("visibilitychange",()=>this.Ec(document.hidden));return{isSuspended:!(!document.hidden&&!t)}}dd(){window.addEventListener("focus",
()=>this.Gb("window-focus"));window.addEventListener("blur",()=>{this.Gb("window-blur",{parentHasFocus:ca()});this.ib=0});window.addEventListener("fullscreenchange",()=>this.zc());window.addEventListener("webkitfullscreenchange",()=>this.zc());window.addEventListener("mozfullscreenchange",()=>this.zc());window.addEventListener("fullscreenerror",h=>this.Ac(h));window.addEventListener("webkitfullscreenerror",h=>this.Ac(h));window.addEventListener("mozfullscreenerror",h=>this.Ac(h));window.addEventListener("keydown",
h=>this.Bd("keydown",h));window.addEventListener("keyup",h=>this.Bd("keyup",h));window.addEventListener("dblclick",h=>this.Cc("dblclick",h,b));window.addEventListener("wheel",h=>this.Hf(h));"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",h=>{this.vc(h);this.Ta("pointerdown",h)}),this.v.Aa&&"undefined"!==typeof window.onpointerrawupdate&&self===self.top?(this.lb=new self.Me(()=>this.gf(),5),this.lb.Ld=!0,window.addEventListener("pointerrawupdate",h=>this.If(h))):window.addEventListener("pointermove",
h=>this.Ta("pointermove",h)),window.addEventListener("pointerup",h=>this.Ta("pointerup",h)),window.addEventListener("pointercancel",h=>this.Ta("pointercancel",h))):(window.addEventListener("mousedown",h=>{this.vc(h);this.Dc("pointerdown",h)}),window.addEventListener("mousemove",h=>this.Dc("pointermove",h)),window.addEventListener("mouseup",h=>this.Dc("pointerup",h)),window.addEventListener("touchstart",h=>{this.vc(h);this.Eb("pointerdown",h)}),window.addEventListener("touchmove",h=>this.Eb("pointermove",
h)),window.addEventListener("touchend",h=>this.Eb("pointerup",h)),window.addEventListener("touchcancel",h=>this.Eb("pointercancel",h)));const e=()=>this.Fc();window.addEventListener("pointerup",e,!0);window.addEventListener("touchend",e,!0);window.addEventListener("click",e,!0);window.addEventListener("keydown",e,!0);window.addEventListener("gamepadconnected",e,!0)}Gb(e,h){v(this,e,h||null,g)}Cb(){return Math.max(window.innerWidth,1)}Bb(){return Math.max(window.innerHeight,1)}Rf(){const e=this.Cb(),
h=this.Bb();this.Gb("window-resize",{innerWidth:e,innerHeight:h,devicePixelRatio:window.devicePixelRatio});this.v.vb()&&(-1!==this.Ma&&clearTimeout(this.Ma),this.Dd(e,h,0))}$f(e,h,p){-1!==this.Ma&&clearTimeout(this.Ma);this.Ma=setTimeout(()=>this.Dd(e,h,p),48)}Dd(e,h,p){const m=this.Cb(),q=this.Bb();this.Ma=-1;m!=e||q!=h?this.Gb("window-resize",{innerWidth:m,innerHeight:q,devicePixelRatio:window.devicePixelRatio}):10>p&&this.$f(m,q,p+1)}Of(e){this.Zc=e.targetOrientation}sg(){const e=this.Zc;if(screen.orientation&&
screen.orientation.lock)screen.orientation.lock(e).catch(h=>console.warn("[Construct 3] Failed to lock orientation: ",h));else try{let h=!1;screen.lockOrientation?h=screen.lockOrientation(e):screen.webkitLockOrientation?h=screen.webkitLockOrientation(e):screen.mozLockOrientation?h=screen.mozLockOrientation(e):screen.msLockOrientation&&(h=screen.msLockOrientation(e));h||console.warn("[Construct 3] Failed to lock orientation")}catch(h){console.warn("[Construct 3] Failed to lock orientation: ",h)}}zc(){const e=
d.ic();e&&"any"!==this.Zc&&this.sg();v(this,"fullscreenchange",{isFullscreen:e,innerWidth:this.Cb(),innerHeight:this.Bb()})}Ac(e){console.warn("[Construct 3] Fullscreen request failed: ",e);v(this,"fullscreenerror",{isFullscreen:d.ic(),innerWidth:this.Cb(),innerHeight:this.Bb()})}Ec(e){e?this.v.rc():this.v.Gc();v(this,"visibilitychange",{hidden:e})}Bd(e,h){"Backspace"===h.key&&O(h);const p=a.get(h.code)||h.code;x(this,e,{code:p,key:h.key,which:h.which,repeat:h.repeat,altKey:h.altKey,ctrlKey:h.ctrlKey,
metaKey:h.metaKey,shiftKey:h.shiftKey,timeStamp:h.timeStamp},b)}Hf(e){v(this,"wheel",{clientX:e.clientX,clientY:e.clientY,pageX:e.pageX,pageY:e.pageY,deltaX:e.deltaX,deltaY:e.deltaY,deltaZ:e.deltaZ,deltaMode:e.deltaMode,timeStamp:e.timeStamp},b)}Cc(e,h,p){Q(h)||x(this,e,{button:h.button,buttons:h.buttons,clientX:h.clientX,clientY:h.clientY,pageX:h.pageX,pageY:h.pageY,timeStamp:h.timeStamp},p)}Dc(e,h){if(!Q(h)){var p=this.ib;"pointerdown"===e&&0!==p?e="pointermove":"pointerup"===e&&0!==h.buttons&&
(e="pointermove");x(this,e,{pointerId:1,pointerType:"mouse",button:h.button,buttons:h.buttons,lastButtons:p,clientX:h.clientX,clientY:h.clientY,pageX:h.pageX,pageY:h.pageY,width:0,height:0,pressure:0,tangentialPressure:0,tiltX:0,tiltY:0,twist:0,timeStamp:h.timeStamp},b);this.ib=h.buttons;this.Cc(h.type,h,c)}}Ta(e,h){if(this.lb&&"pointermove"!==e){var p=this.lb;p.ab||(D(p),p.Pb=Date.now())}p=0;"mouse"===h.pointerType&&(p=this.ib);x(this,e,{pointerId:h.pointerId,pointerType:h.pointerType,button:h.button,
buttons:h.buttons,lastButtons:p,clientX:h.clientX,clientY:h.clientY,pageX:h.pageX,pageY:h.pageY,width:h.width||0,height:h.height||0,pressure:h.pressure||0,tangentialPressure:h.tangentialPressure||0,tiltX:h.tiltX||0,tiltY:h.tiltY||0,twist:h.twist||0,timeStamp:h.timeStamp},b);"mouse"===h.pointerType&&(p="mousemove","pointerdown"===e?p="mousedown":"pointerup"===e&&(p="pointerup"),this.Cc(p,h,c),this.ib=h.buttons)}If(e){this.Sc=e;e=this.lb;if(-1===e.Na){var h=Date.now(),p=h-e.Pb,m=e.yg;p>=m&&e.Ld?(e.Pb=
h,e.ab=!0,e.Jc(),e.ab=!1):e.Na=self.setTimeout(e.ce,Math.max(m-p,4))}}gf(){this.Ta("pointermove",this.Sc);this.Sc=null}Eb(e,h){for(let p=0,m=h.changedTouches.length;p<m;++p){const q=h.changedTouches[p];x(this,e,{pointerId:q.identifier,pointerType:"touch",button:0,buttons:0,lastButtons:0,clientX:q.clientX,clientY:q.clientY,pageX:q.pageX,pageY:q.pageY,width:2*(q.radiusX||q.webkitRadiusX||0),height:2*(q.radiusY||q.webkitRadiusY||0),pressure:q.force||q.webkitForce||0,tangentialPressure:0,tiltX:0,tiltY:0,
twist:q.rotationAngle||0,timeStamp:h.timeStamp},b)}}vc(e){window!==window.top&&window.focus();this.zd(e.target)&&document.activeElement&&!this.zd(document.activeElement)&&document.activeElement.blur()}zd(e){return!e||e===document||e===window||e===document.body||"canvas"===e.tagName.toLowerCase()}Ye(){this.Id||(this.Id=!0,window.addEventListener("deviceorientation",e=>this.zf(e)),window.addEventListener("deviceorientationabsolute",e=>this.Af(e)))}Xe(){this.Hd||(this.Hd=!0,window.addEventListener("devicemotion",
e=>this.yf(e)))}zf(e){v(this,"deviceorientation",{absolute:!!e.absolute,alpha:e.alpha||0,beta:e.beta||0,gamma:e.gamma||0,timeStamp:e.timeStamp,webkitCompassHeading:e.webkitCompassHeading,webkitCompassAccuracy:e.webkitCompassAccuracy},b)}Af(e){v(this,"deviceorientationabsolute",{absolute:!!e.absolute,alpha:e.alpha||0,beta:e.beta||0,gamma:e.gamma||0,timeStamp:e.timeStamp},b)}yf(e){let h=null;var p=e.acceleration;p&&(h={x:p.x||0,y:p.y||0,z:p.z||0});p=null;var m=e.accelerationIncludingGravity;m&&(p={x:m.x||
0,y:m.y||0,z:m.z||0});m=null;const q=e.rotationRate;q&&(m={alpha:q.alpha||0,beta:q.beta||0,gamma:q.gamma||0});v(this,"devicemotion",{acceleration:h,accelerationIncludingGravity:p,rotationRate:m,interval:e.interval,timeStamp:e.timeStamp},b)}Qf(e){const h=this.v,p=h.I;p.style.width=e.styleWidth+"px";p.style.height=e.styleHeight+"px";p.style.marginLeft=e.marginLeft+"px";p.style.marginTop=e.marginTop+"px";h.md();this.Qd&&(p.style.display="",this.Qd=!1)}Ef(e){const h=e.url;e=e.filename;const p=document.createElement("a"),
m=document.body;p.textContent=e;p.href=h;p.download=e;m.appendChild(p);p.click();m.removeChild(p)}async Kf(e){var h=e.imageBitmapOpts;e=await self.C3_RasterSvgImageBlob(e.blob,e.imageWidth,e.imageHeight,e.surfaceWidth,e.surfaceHeight);h=h?await createImageBitmap(e,h):await createImageBitmap(e);return{imageBitmap:h,transferables:[h]}}async Df(e){return await self.C3_GetSvgImageSize(e.blob)}async sf(e){await ha(e.url)}Fc(){var e=[...this.Ha];this.Ha.clear();if(!this.na)for(const h of e)(e=h.play())&&
e.catch(()=>{this.Sb.has(h)||this.Ha.add(h)})}ua(e){if("function"!==typeof e.play)throw Error("missing play function");this.Sb.delete(e);let h;try{h=e.play()}catch(p){this.Ha.add(e);return}h&&h.catch(()=>{this.Sb.has(e)||this.Ha.add(e)})}Ca(e){this.Ha.delete(e);this.Sb.add(e)}yb(e){this.na=!!e}xf(e){if(e.show){this.wa||(this.wa=document.createElement("div"),this.wa.id="inspectOutline",document.body.appendChild(this.wa));var h=this.wa;h.style.display="";h.style.left=e.left-1+"px";h.style.top=e.top-
1+"px";h.style.width=e.width+2+"px";h.style.height=e.height+2+"px";h.textContent=e.name}else this.wa&&(this.wa.style.display="none")}Lf(){window.C3_RegisterSW&&window.C3_RegisterSW()}Cd(e){window.c3_postToMessagePort&&(e.from="runtime",window.c3_postToMessagePort(e))}qf(e,h){return this.v.nd(this.Wa,"js-invoke-function",{name:e,params:h},void 0,void 0)}tf(e){alert(e.message)}})}"use strict";
{const d=document.currentScript.src;self.Ie=class{constructor(a){this.Wb=a;this.X=d?d.substr(0,d.lastIndexOf("/")+1):a.X;this.Ag=Math.min(navigator.hardwareConcurrency||2,16);this.Lc=null;this.Sd=[];this.Wc=this.Pc=null}async Ee(){if(this.xg)throw Error("already initialised");this.xg=!0;var a=this.Wb.uc("dispatchworker.js");this.Lc=await this.Wb.bc(a,this.X,{name:"DispatchWorker"});a=new MessageChannel;this.Pc=a.port1;this.Lc.postMessage({type:"_init","in-port":a.port2},[a.port2]);this.Wc=await this.ud()}async ud(){const a=
this.Sd.length;var b=this.Wb.uc("jobworker.js");b=await this.Wb.bc(b,this.X,{name:"JobWorker"+a});const c=new MessageChannel,g=new MessageChannel;this.Lc.postMessage({type:"_addJobWorker",port:c.port1},[c.port1]);b.postMessage({type:"init",number:a,"dispatch-port":c.port2,"output-port":g.port2},[c.port2,g.port2]);this.Sd.push(b);return g.port1}Ce(){return{inputPort:this.Pc,outputPort:this.Wc,maxNumWorkers:this.Ag}}De(){return[this.Pc,this.Wc]}}}"use strict";
window.C3_IsSupported&&(window.c3_runtimeInterface=new self.ka({Og:"undefined"!==typeof OffscreenCanvas,Pg:"workermain.js",Oa:["scripts/c3runtime.js"],Lg:"scripts/",cd:[],de:"html5"}));"use strict";
{const d=180/Math.PI;self.da=class extends self.rb{constructor(a){super(a,"audio");this.Lb=this.f=null;this.Nb=this.Oc=!1;this.pa=()=>this.tg();this.ba=[];this.C=[];this.ga=null;this.Td="";this.Ud=-1;this.kb=new Map;this.Tc=1;this.na=!1;this.$c=0;this.Yb=1;this.Mc=0;this.Wd="HRTF";this.Md="inverse";this.Xd=600;this.Vd=1E4;this.Zd=1;this.Od=this.Xc=!1;this.Fg=this.v.Ge();this.ca=new Map;this.Ea=new Set;this.Qc=!1;this.Uc="";this.ya=null;self.C3Audio_OnMicrophoneStream=(b,c)=>this.Gf(b,c);this.Kb=null;
self.C3Audio_GetOutputStream=()=>this.Cf();self.C3Audio_DOMInterface=this;B(this,[["create-audio-context",b=>this.cf(b)],["play",b=>this.Tf(b)],["stop",b=>this.Hc(b)],["stop-all",()=>this.qg()],["set-paused",b=>this.jg(b)],["set-volume",b=>this.og(b)],["fade-volume",b=>this.hf(b)],["set-master-volume",b=>this.hg(b)],["set-muted",b=>this.ig(b)],["set-silent",b=>this.lg(b)],["set-looping",b=>this.gg(b)],["set-playback-rate",b=>this.kg(b)],["seek",b=>this.ag(b)],["preload",b=>this.Uf(b)],["unload",b=>
this.ug(b)],["unload-all",()=>this.vg()],["set-suspended",b=>this.mg(b)],["add-effect",b=>this.sd(b)],["set-effect-param",b=>this.dg(b)],["remove-effects",b=>this.Wf(b)],["tick",b=>this.Pf(b)],["load-state",b=>this.Bc(b)]])}async cf(a){a.isiOSCordova&&(this.Xc=!0);this.$c=a.timeScaleMode;this.Wd=["equalpower","HRTF","soundfield"][a.panningModel];this.Md=["linear","inverse","exponential"][a.distanceModel];this.Xd=a.refDistance;this.Vd=a.maxDistance;this.Zd=a.rolloffFactor;var b={latencyHint:a.latencyHint};
if("undefined"!==typeof AudioContext)this.f=new AudioContext(b);else if("undefined"!==typeof webkitAudioContext)this.f=new webkitAudioContext(b);else throw Error("Web Audio API not supported");this.td();this.f.onstatechange=()=>{"running"!==this.f.state&&this.td()};this.Lb=this.f.createGain();this.Lb.connect(this.f.destination);b=a.listenerPos;this.f.listener.setPosition(b[0],b[1],b[2]);this.f.listener.setOrientation(0,0,1,0,-1,0);self.C3_GetAudioContextCurrentTime=()=>this.cc();try{await Promise.all(a.preloadList.map(c=>
this.Ab(c.originalUrl,c.url,c.type,!1)))}catch(c){console.error("[Construct 3] Preloading sounds failed: ",c)}return{sampleRate:this.f.sampleRate}}td(){this.Nb||(this.Oc=!1,window.addEventListener("pointerup",this.pa,!0),window.addEventListener("touchend",this.pa,!0),window.addEventListener("click",this.pa,!0),window.addEventListener("keydown",this.pa,!0),this.Nb=!0)}ef(){this.Nb&&(this.Oc=!0,window.removeEventListener("pointerup",this.pa,!0),window.removeEventListener("touchend",this.pa,!0),window.removeEventListener("click",
this.pa,!0),window.removeEventListener("keydown",this.pa,!0),this.Nb=!1)}tg(){if(!this.Oc){var a=this.f;"suspended"===a.state&&a.resume&&a.resume();var b=a.createBuffer(1,220,22050),c=a.createBufferSource();c.buffer=b;c.connect(a.destination);c.start(0);"running"===a.state&&this.ef()}}W(){return this.f}cc(){return this.f.currentTime}ra(){return this.Lb}kd(a){return(a=this.ca.get(a.toLowerCase()))?a[0].N():this.ra()}fe(a,b){a=a.toLowerCase();let c=this.ca.get(a);c||(c=[],this.ca.set(a,c));b.fg(c.length);
b.ng(a);c.push(b);this.Fd(a)}Fd(a){let b=this.ra();const c=this.ca.get(a);if(c&&c.length){b=c[0].N();for(let g=0,l=c.length;g<l;++g){const t=c[g];g+1===l?t.P(this.ra()):t.P(c[g+1].N())}}for(const g of this.ja(a))g.Ne(b);this.ya&&this.Uc===a&&(this.ya.disconnect(),this.ya.connect(b))}tb(){return this.Tc}ub(){return this.na}eg(){this.Od=!0}xe(a,b){return b?this.v.wg(a).then(c=>{const g=this.f.createBuffer(1,c.length,48E3);g.getChannelData(0).set(c);return g}):new Promise((c,g)=>{this.f.decodeAudioData(a,
c,g)})}ua(a){this.v.ua(a)}Ca(a){this.v.Ca(a)}od(a){let b=0;for(let c=0,g=this.C.length;c<g;++c){const l=this.C[c];this.C[b]=l;l.J===a?l.c():++b}this.C.length=b}Oe(){let a=0;for(let b=0,c=this.ba.length;b<c;++b){const g=this.ba[b];this.ba[a]=g;g.sa()?g.c():++a}this.ba.length=a}*ja(a){if(a)for(const b of this.C)self.da.ye(b.$,a)&&(yield b);else this.ga&&!this.ga.R()&&(yield this.ga)}async Ab(a,b,c,g,l){for(const t of this.ba)if(t.Ra()===b)return await R(t),t;if(l)return null;g&&(this.Xc||this.Od)&&
this.Oe();l="audio/webm; codecs=opus"===c&&!this.Fg;g&&l&&this.eg();a=!g||this.Xc||l?new self.te(this,a,b,c,g,l):new self.re(this,a,b,c,g);this.ba.push(a);await R(a);return a}async tc(a,b,c,g,l){for(const t of this.C)if(t.Ra()===b&&(t.$b()||l))return t.Re(g),t;a=await this.Ab(a,b,c,l);g="html5"===a.Ic?new self.se(a.i,a,g):new self.ue(a.i,a,g);this.C.push(g);return g}Ve(a){let b=this.kb.get(a);if(!b){let c=null;b={bd:0,promise:new Promise(g=>c=g),resolve:c};this.kb.set(a,b)}b.bd++}Xf(a){const b=this.kb.get(a);
if(!b)throw Error("expected pending tag");b.bd--;0===b.bd&&(b.resolve(),this.kb.delete(a))}qc(a){a||(a=this.Td);return(a=this.kb.get(a))?a.promise:Promise.resolve()}Db(){if(0<this.Ea.size)C(this);else for(const a of this.C)if(a.ld()){C(this);break}}ta(){for(var a of this.Ea)a.ta();a=this.cc();for(var b of this.C)b.ta(a);b=this.C.filter(c=>c.ld()).map(c=>c.Qa());v(this,"state",{tickCount:this.Ud,audioInstances:b,analysers:[...this.Ea].map(c=>c.Ae())});0===b.length&&0===this.Ea.size&&this.Ob&&(this.v.Yf(this.be),
this.Ob=!1)}lc(a,b,c){v(this,"trigger",{type:a,tag:b,aiid:c})}async Tf(a){const b=a.originalUrl,c=a.url,g=a.type,l=a.isMusic,t=a.tag,e=a.isLooping,h=a.vol,p=a.pos,m=a.panning;let q=a.off;0<q&&!a.trueClock&&(this.f.getOutputTimestamp?(a=this.f.getOutputTimestamp(),q=q-a.performanceTime/1E3+a.contextTime):q=q-performance.now()/1E3+this.f.currentTime);this.Td=t;this.Ve(t);try{this.ga=await this.tc(b,c,g,t,l),m?(this.ga.xb(!0),this.ga.Qe(m.x,m.y,m.angle,m.innerAngle,m.outerAngle,m.outerGain),m.hasOwnProperty("uid")&&
this.ga.Se(m.uid)):this.ga.xb(!1),this.ga.Play(e,h,p,q)}catch(f){console.error("[Construct 3] Audio: error starting playback: ",f);return}finally{this.Xf(t)}C(this)}Hc(a){a=a.tag;for(const b of this.ja(a))b.la()}qg(){for(const a of this.C)a.la()}jg(a){const b=a.tag;a=a.paused;for(const c of this.ja(b))a?c.Sa():c.wb();this.Db()}og(a){const b=a.tag;a=a.vol;for(const c of this.ja(b))c.zb(a)}async hf(a){const b=a.tag,c=a.vol,g=a.duration;a=a.stopOnEnd;await this.qc(b);for(const l of this.ja(b))l.ze(c,
g,a);this.Db()}hg(a){this.Tc=a.vol;for(const b of this.C)b.Ib()}ig(a){const b=a.tag;a=a.isMuted;for(const c of this.ja(b))c.pd(a)}lg(a){this.na=a.isSilent;this.v.yb(this.na);for(const b of this.C)b.Hb()}gg(a){const b=a.tag;a=a.isLooping;for(const c of this.ja(b))c.oc(a)}async kg(a){const b=a.tag;a=a.rate;await this.qc(b);for(const c of this.ja(b))c.rd(a)}async ag(a){const b=a.tag;a=a.pos;await this.qc(b);for(const c of this.ja(b))c.nc(a)}async Uf(a){const b=a.originalUrl,c=a.url,g=a.type;a=a.isMusic;
try{await this.tc(b,c,g,"",a)}catch(l){console.error("[Construct 3] Audio: error preloading: ",l)}}async ug(a){if(a=await this.Ab("",a.url,a.type,a.isMusic,!0))a.c(),a=this.ba.indexOf(a),-1!==a&&this.ba.splice(a,1)}vg(){for(const a of this.ba)a.c();this.ba.length=0}mg(a){a=a.isSuspended;!a&&this.f.resume&&this.f.resume();for(const b of this.C)b.pc(a);a&&this.f.suspend&&this.f.suspend()}Pf(a){this.Yb=a.timeScale;this.Mc=a.gameTime;this.Ud=a.tickCount;if(0!==this.$c)for(var b of this.C)b.Da();(b=a.listenerPos)&&
this.f.listener.setPosition(b[0],b[1],b[2]);for(const c of a.instPans){a=c.uid;for(const g of this.C)g.fa===a&&g.qd(c.x,c.y,c.angle)}}async sd(a){var b=a.type;const c=a.tag;var g=a.params;if("filter"===b)g=new self.le(this,...g);else if("delay"===b)g=new self.je(this,...g);else if("convolution"===b){b=null;try{b=await this.Ab(a.bufferOriginalUrl,a.bufferUrl,a.bufferType,!1)}catch(l){console.log("[Construct 3] Audio: error loading convolution: ",l);return}g=new self.ie(this,b.aa,...g);g.bg(a.bufferOriginalUrl,
a.bufferType)}else if("flanger"===b)g=new self.me(this,...g);else if("phaser"===b)g=new self.oe(this,...g);else if("gain"===b)g=new self.ne(this,...g);else if("tremolo"===b)g=new self.qe(this,...g);else if("ringmod"===b)g=new self.pe(this,...g);else if("distortion"===b)g=new self.ke(this,...g);else if("compressor"===b)g=new self.he(this,...g);else if("analyser"===b)g=new self.ge(this,...g);else throw Error("invalid effect type");this.fe(c,g);this.Ed()}dg(a){const b=a.index,c=a.param,g=a.value,l=a.ramp,
t=a.time;a=this.ca.get(a.tag);!a||0>b||b>=a.length||(a[b].Y(c,g,l,t),this.Ed())}Wf(a){a=a.tag.toLowerCase();const b=this.ca.get(a);if(b&&b.length){for(const c of b)c.c();this.ca.delete(a);this.Fd(a)}}Ue(a){this.Ea.add(a);this.Db()}Vf(a){this.Ea.delete(a)}Ed(){this.Qc||(this.Qc=!0,Promise.resolve().then(()=>this.ff()))}ff(){const a={};for(const [b,c]of this.ca)a[b]=c.map(g=>g.Qa());v(this,"fxstate",{fxstate:a});this.Qc=!1}async Bc(a){const b=a.saveLoadMode;if(3!==b)for(var c of this.C)c.sa()&&1===
b||(c.sa()||2!==b)&&c.la();for(const g of this.ca.values())for(const l of g)l.c();this.ca.clear();this.Yb=a.timeScale;this.Mc=a.gameTime;c=a.listenerPos;this.f.listener.setPosition(c[0],c[1],c[2]);this.na=a.isSilent;this.v.yb(this.na);this.Tc=a.masterVolume;c=[];for(const g of Object.values(a.effects))c.push(Promise.all(g.map(l=>this.sd(l))));await Promise.all(c);await Promise.all(a.playing.map(g=>this.rf(g,b)));this.Db()}async rf(a,b){if(3!==b){var c=a.bufferOriginalUrl,g=a.bufferUrl,l=a.bufferType,
t=a.isMusic,e=a.tag,h=a.isLooping,p=a.volume,m=a.playbackTime;if(!t||1!==b)if(t||2!==b){b=null;try{b=await this.tc(c,g,l,e,t)}catch(q){console.error("[Construct 3] Audio: error loading audio state: ",q);return}b.Le(a.pan);b.Play(h,p,m,0);a.isPlaying||b.Sa();b.xc(a)}}}Gf(a,b){this.ya&&this.ya.disconnect();this.Uc=b.toLowerCase();this.ya=this.f.createMediaStreamSource(a);this.ya.connect(this.kd(this.Uc))}Cf(){this.Kb||(this.Kb=this.f.createMediaStreamDestination(),this.Lb.connect(this.Kb));return this.Kb.stream}static ye(a,
b){return a.length!==b.length?!1:a===b?!0:a.toLowerCase()===b.toLowerCase()}static Te(a){return a*d}static we(a){return Math.pow(10,a/20)}static hd(a){return Math.max(Math.min(self.da.we(a),1),0)}static Ke(a){return Math.log(a)/Math.log(10)*20}static Je(a){return self.da.Ke(Math.max(Math.min(a,1),0))}static Hg(a,b){return 1-Math.exp(-b*a)}};self.ka.qa(self.da)}"use strict";function R(d){d.Qb||(d.Qb=d.wc());return d.Qb}
self.ed=class{constructor(d,a,b,c,g){this.i=d;this.Cg=a;this.za=b;this.O=c;this.zg=g;this.Ic="";this.Qb=null}c(){this.Qb=this.i=null}wc(){}W(){return this.i.W()}ec(){return this.Cg}Ra(){return this.za}dc(){return this.O}sa(){return this.zg}ea(){}};"use strict";
self.re=class extends self.ed{constructor(d,a,b,c,g){super(d,a,b,c,g);this.Ic="html5";this.H=new Audio;this.H.crossOrigin="anonymous";this.H.autoplay=!1;this.H.preload="auto";this.eb=this.fb=null;this.H.addEventListener("canplaythrough",()=>!0);this.jb=this.W().createGain();this.hb=null;this.H.addEventListener("canplay",()=>{this.fb&&(this.fb(),this.eb=this.fb=null);!this.hb&&this.H&&(this.hb=this.W().createMediaElementSource(this.H),this.hb.connect(this.jb))});this.onended=null;this.H.addEventListener("ended",
()=>{if(this.onended)this.onended()});this.H.addEventListener("error",l=>{console.error(`[Construct 3] Audio '${this.za}' error: `,l);this.eb&&(this.eb(l),this.eb=this.fb=null)})}c(){this.i.od(this);this.jb.disconnect();this.jb=null;this.hb.disconnect();this.hb=null;this.H&&!this.H.paused&&this.H.pause();this.H=this.onended=null;super.c()}wc(){return new Promise((d,a)=>{this.fb=d;this.eb=a;this.H.src=this.za})}M(){return this.H}ea(){return this.H.duration}};"use strict";
async function ia(d){if(d.va)return d.va;var a=d.i.v;if("cordova"===a.U&&a.He(d.za)&&"file:"===location.protocol)d.va=await a.ac(d.za);else{a=await fetch(d.za);if(!a.ok)throw Error(`error fetching audio data: ${a.status} ${a.statusText}`);d.va=await a.arrayBuffer()}}async function ja(d){if(d.aa)return d.aa;d.aa=await d.i.xe(d.va,d.Bg);d.va=null}
self.te=class extends self.ed{constructor(d,a,b,c,g,l){super(d,a,b,c,g);this.Ic="webaudio";this.aa=this.va=null;this.Bg=!!l}c(){this.i.od(this);this.aa=this.va=null;super.c()}async wc(){try{await ia(this),await ja(this)}catch(d){console.error(`[Construct 3] Failed to load audio '${this.za}': `,d)}}ea(){return this.aa?this.aa.duration:0}};"use strict";
{let d=0;self.fd=class{constructor(a,b,c){this.i=a;this.J=b;this.$=c;this.Jb=d++;this.K=this.W().createGain();this.K.connect(this.ra());this.A=null;this.bb=!1;this.F=!0;this.V=this.ia=this.D=!1;this.nb=1;this.Fa=!1;this.Z=1;a=this.i.$c;this.Rc=1===a&&!this.sa()||2===a;this.Za=this.fa=-1;this.ae=!1}c(){this.J=this.i=null;this.A&&(this.A.disconnect(),this.A=null);this.K.disconnect();this.K=null}W(){return this.i.W()}ra(){return this.i.kd(this.$)}tb(){return this.i.tb()}sb(){return this.Rc?this.i.Mc:
performance.now()/1E3}ec(){return this.J.ec()}Ra(){return this.J.Ra()}dc(){return this.J.dc()}sa(){return this.J.sa()}Re(a){this.$=a}R(){}$b(){}IsPlaying(){return!this.F&&!this.D&&!this.R()}ld(){return!this.F&&!this.R()}Ba(){}ea(){return this.J.ea()}Play(){}la(){}Sa(){}wb(){}zb(a){this.nb=a;this.K.gain.cancelScheduledValues(0);this.Za=-1;this.K.gain.value=this.fc()}ze(a,b,c){if(!this.Fa){a*=this.tb();var g=this.K.gain;g.cancelScheduledValues(0);var l=this.i.cc();b=l+b;g.setValueAtTime(g.value,l);
g.linearRampToValueAtTime(a,b);this.nb=a;this.Za=b;this.ae=c}}Ib(){this.zb(this.nb)}ta(a){-1!==this.Za&&a>=this.Za&&(this.Za=-1,this.ae&&this.la(),this.i.lc("fade-ended",this.$,this.Jb))}fc(){const a=this.nb*this.tb();return isFinite(a)?a:0}pd(a){a=!!a;this.Fa!==a&&(this.Fa=a,this.Hb())}ub(){return this.i.ub()}Hb(){}oc(){}rd(a){this.Z!==a&&(this.Z=a,this.Da())}Da(){}nc(){}pc(){}xb(a){a=!!a;this.bb!==a&&((this.bb=a)?(this.A||(this.A=this.W().createPanner(),this.A.panningModel=this.i.Wd,this.A.distanceModel=
this.i.Md,this.A.refDistance=this.i.Xd,this.A.maxDistance=this.i.Vd,this.A.rolloffFactor=this.i.Zd),this.K.disconnect(),this.K.connect(this.A),this.A.connect(this.ra())):(this.A.disconnect(),this.K.disconnect(),this.K.connect(this.ra())))}Qe(a,b,c,g,l,t){this.bb&&(this.qd(a,b,c),a=self.da.Te,this.A.coneInnerAngle=a(g),this.A.coneOuterAngle=a(l),this.A.coneOuterGain=t)}qd(a,b,c){this.bb&&(this.A.setPosition(a,b,0),this.A.setOrientation(Math.cos(c),Math.sin(c),0))}Se(a){this.fa=a}hc(){}Ne(a){const b=
this.A||this.K;b.disconnect();b.connect(a)}Qa(){return{aiid:this.Jb,tag:this.$,duration:this.ea(),volume:this.nb,isPlaying:this.IsPlaying(),playbackTime:this.Ba(),playbackRate:this.Z,uid:this.fa,bufferOriginalUrl:this.ec(),bufferUrl:"",bufferType:this.dc(),isMusic:this.sa(),isLooping:this.V,isMuted:this.Fa,resumePosition:this.hc(),pan:this.Be()}}xc(a){this.rd(a.playbackRate);this.pd(a.isMuted)}Be(){if(!this.A)return null;const a=this.A;return{pos:[a.positionX.value,a.positionY.value,a.positionZ.value],
orient:[a.orientationX.value,a.orientationY.value,a.orientationZ.value],cia:a.coneInnerAngle,coa:a.coneOuterAngle,cog:a.coneOuterGain,uid:this.fa}}Le(a){a?(this.xb(!0),a=this.A,a.setPosition(...a.pos),a.setOrientation(...a.orient),a.coneInnerAngle=a.cia,a.coneOuterAngle=a.coa,a.coneOuterGain=a.cog,this.fa=a.uid):this.xb(!1)}}}"use strict";
self.se=class extends self.fd{constructor(d,a,b){super(d,a,b);this.J.jb.connect(this.K);this.J.onended=()=>this.yc()}c(){this.la();this.J.jb.disconnect();super.c()}M(){return this.J.M()}yc(){this.F=!0;this.fa=-1;this.i.lc("ended",this.$,this.Jb)}R(){return this.M().ended}$b(){return this.F?!0:this.R()}Ba(d){let a=this.M().currentTime;d&&(a*=this.Z);this.V||(a=Math.min(a,this.ea()));return a}Play(d,a,b){const c=this.M();1!==c.playbackRate&&(c.playbackRate=1);c.loop!==d&&(c.loop=d);this.zb(a);c.muted&&
(c.muted=!1);if(c.currentTime!==b)try{c.currentTime=b}catch(g){console.warn(`[Construct 3] Exception seeking audio '${this.J.Ra()}' to position '${b}': `,g)}this.i.ua(c);this.D=this.F=!1;this.V=d;this.Z=1}la(){const d=this.M();d.paused||d.pause();this.i.Ca(d);this.F=!0;this.D=!1;this.fa=-1}Sa(){if(!(this.D||this.F||this.R())){var d=this.M();d.paused||d.pause();this.i.Ca(d);this.D=!0}}wb(){!this.D||this.F||this.R()||(this.i.ua(this.M()),this.D=!1)}Hb(){this.M().muted=this.Fa||this.ub()}oc(d){d=!!d;
this.V!==d&&(this.V=d,this.M().loop=d)}Da(){let d=this.Z;this.Rc&&(d*=this.i.Yb);try{this.M().playbackRate=d}catch(a){console.warn(`[Construct 3] Unable to set playback rate '${d}':`,a)}}nc(d){if(!this.F&&!this.R())try{this.M().currentTime=d}catch(a){console.warn(`[Construct 3] Error seeking audio to '${d}': `,a)}}hc(){return this.Ba()}pc(d){d?this.IsPlaying()?(this.M().pause(),this.ia=!0):this.ia=!1:this.ia&&(this.i.ua(this.M()),this.ia=!1)}};"use strict";
function S(d){d.j&&d.j.disconnect();d.j=null;d.Ua=null}
self.ue=class extends self.fd{constructor(d,a,b){super(d,a,b);this.j=null;this.Tb=c=>this.yc(c);this.Nc=!0;this.Ua=null;this.L=this.Xb=0;this.Vc=1}c(){this.la();S(this);this.Tb=null;super.c()}yc(d){this.D||this.ia||d.target!==this.Ua||(this.F=this.Nc=!0,this.fa=-1,S(this),this.i.lc("ended",this.$,this.Jb))}R(){return!this.F&&this.j&&this.j.loop||this.D?!1:this.Nc}$b(){return!this.j||this.F?!0:this.R()}Ba(d){let a;a=this.D?this.L:this.sb()-this.Xb;d&&(a*=this.Z);this.V||(a=Math.min(a,this.ea()));return a}Play(d,
a,b,c){this.Vc=1;this.zb(a);S(this);this.j=this.W().createBufferSource();this.j.buffer=this.J.aa;this.j.connect(this.K);this.Ua=this.j;this.j.onended=this.Tb;this.j.loop=d;this.j.start(c,b);this.D=this.F=this.Nc=!1;this.V=d;this.Z=1;this.Xb=this.sb()-b}la(){if(this.j)try{this.j.stop(0)}catch(d){}this.F=!0;this.D=!1;this.fa=-1}Sa(){this.D||this.F||this.R()||(this.L=this.Ba(!0),this.V&&(this.L%=this.ea()),this.D=!0,this.j.stop(0))}wb(){!this.D||this.F||this.R()||(S(this),this.j=this.W().createBufferSource(),
this.j.buffer=this.J.aa,this.j.connect(this.K),this.Ua=this.j,this.j.onended=this.Tb,this.j.loop=this.V,this.Ib(),this.Da(),this.Xb=this.sb()-this.L/(this.Z||.001),this.j.start(0,this.L),this.D=!1)}fc(){return super.fc()*this.Vc}Hb(){this.Vc=this.Fa||this.ub()?0:1;this.Ib()}oc(d){d=!!d;this.V!==d&&(this.V=d,this.j&&(this.j.loop=d))}Da(){let d=this.Z;this.Rc&&(d*=this.i.Yb);this.j&&(this.j.playbackRate.value=d)}nc(d){this.F||this.R()||(this.D?this.L=d:(this.Sa(),this.L=d,this.wb()))}hc(){return this.L}pc(d){d?
this.IsPlaying()?(this.ia=!0,this.L=this.Ba(!0),this.V&&(this.L%=this.ea()),this.j.stop(0)):this.ia=!1:this.ia&&(S(this),this.j=this.W().createBufferSource(),this.j.buffer=this.J.aa,this.j.connect(this.K),this.Ua=this.j,this.j.onended=this.Tb,this.j.loop=this.V,this.Ib(),this.Da(),this.Xb=this.sb()-this.L/(this.Z||.001),this.j.start(0,this.L),this.ia=!1)}xc(d){super.xc(d);this.L=d.resumePosition}};"use strict";
{class d{constructor(a){this.i=a;this.f=a.W();this.Pd=-1;this.O=this.$="";this.g=null}c(){this.f=null}fg(a){this.Pd=a}ng(a){this.$=a}o(){return this.f.createGain()}N(){}P(){}m(a,b,c,g){a.cancelScheduledValues(0);if(0===g)a.value=b;else{var l=this.f.currentTime;g+=l;switch(c){case 0:a.setValueAtTime(b,g);break;case 1:a.setValueAtTime(a.value,l);a.linearRampToValueAtTime(b,g);break;case 2:a.setValueAtTime(a.value,l),a.exponentialRampToValueAtTime(b,g)}}}Qa(){return{type:this.O,tag:this.$,params:this.g}}}
self.le=class extends d{constructor(a,b,c,g,l,t,e){super(a);this.O="filter";this.g=[b,c,g,l,t,e];this.l=this.o();this.b=this.o();this.b.gain.value=e;this.a=this.o();this.a.gain.value=1-e;this.u=this.f.createBiquadFilter();this.u.type=b;this.u.frequency.value=c;this.u.detune.value=g;this.u.Q.value=l;this.u.gain.vlaue=t;this.l.connect(this.u);this.l.connect(this.a);this.u.connect(this.b)}c(){this.l.disconnect();this.u.disconnect();this.b.disconnect();this.a.disconnect();super.c()}P(a){this.b.disconnect();
this.b.connect(a);this.a.disconnect();this.a.connect(a)}N(){return this.l}Y(a,b,c,g){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[5]=b;this.m(this.b.gain,b,c,g);this.m(this.a.gain,1-b,c,g);break;case 1:this.g[1]=b;this.m(this.u.frequency,b,c,g);break;case 2:this.g[2]=b;this.m(this.u.detune,b,c,g);break;case 3:this.g[3]=b;this.m(this.u.Q,b,c,g);break;case 4:this.g[4]=b,this.m(this.u.gain,b,c,g)}}};self.je=class extends d{constructor(a,b,c,g){super(a);this.O="delay";this.g=[b,c,g];this.l=
this.o();this.b=this.o();this.b.gain.value=g;this.a=this.o();this.a.gain.value=1-g;this.gb=this.o();this.S=this.f.createDelay(b);this.S.delayTime.value=b;this.Ya=this.o();this.Ya.gain.value=c;this.l.connect(this.gb);this.l.connect(this.a);this.gb.connect(this.b);this.gb.connect(this.S);this.S.connect(this.Ya);this.Ya.connect(this.gb)}c(){this.l.disconnect();this.b.disconnect();this.a.disconnect();this.gb.disconnect();this.S.disconnect();this.Ya.disconnect();super.c()}P(a){this.b.disconnect();this.b.connect(a);
this.a.disconnect();this.a.connect(a)}N(){return this.l}Y(a,b,c,g){const l=self.da.hd;switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[2]=b;this.m(this.b.gain,b,c,g);this.m(this.a.gain,1-b,c,g);break;case 4:this.g[1]=l(b);this.m(this.Ya.gain,l(b),c,g);break;case 5:this.g[0]=b,this.m(this.S.delayTime,b,c,g)}}};self.ie=class extends d{constructor(a,b,c,g){super(a);this.O="convolution";this.g=[c,g];this.Kd=this.Jd="";this.l=this.o();this.b=this.o();this.b.gain.value=g;this.a=this.o();this.a.gain.value=
1-g;this.Xa=this.f.createConvolver();this.Xa.normalize=c;this.Xa.buffer=b;this.l.connect(this.Xa);this.l.connect(this.a);this.Xa.connect(this.b)}c(){this.l.disconnect();this.Xa.disconnect();this.b.disconnect();this.a.disconnect();super.c()}P(a){this.b.disconnect();this.b.connect(a);this.a.disconnect();this.a.connect(a)}N(){return this.l}Y(a,b,c,g){switch(a){case 0:b=Math.max(Math.min(b/100,1),0),this.g[1]=b,this.m(this.b.gain,b,c,g),this.m(this.a.gain,1-b,c,g)}}bg(a,b){this.Jd=a;this.Kd=b}Qa(){const a=
super.Qa();a.bufferOriginalUrl=this.Jd;a.bufferUrl="";a.bufferType=this.Kd;return a}};self.me=class extends d{constructor(a,b,c,g,l,t){super(a);this.O="flanger";this.g=[b,c,g,l,t];this.l=this.o();this.a=this.o();this.a.gain.value=1-t/2;this.b=this.o();this.b.gain.value=t/2;this.$a=this.o();this.$a.gain.value=l;this.S=this.f.createDelay(b+c);this.S.delayTime.value=b;this.s=this.f.createOscillator();this.s.frequency.value=g;this.G=this.o();this.G.gain.value=c;this.l.connect(this.S);this.l.connect(this.a);
this.S.connect(this.b);this.S.connect(this.$a);this.$a.connect(this.S);this.s.connect(this.G);this.G.connect(this.S.delayTime);this.s.start(0)}c(){this.s.stop(0);this.l.disconnect();this.S.disconnect();this.s.disconnect();this.G.disconnect();this.a.disconnect();this.b.disconnect();this.$a.disconnect();super.c()}P(a){this.b.disconnect();this.b.connect(a);this.a.disconnect();this.a.connect(a)}N(){return this.l}Y(a,b,c,g){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[4]=b;this.m(this.b.gain,
b/2,c,g);this.m(this.a.gain,1-b/2,c,g);break;case 6:this.g[1]=b/1E3;this.m(this.G.gain,b/1E3,c,g);break;case 7:this.g[2]=b;this.m(this.s.frequency,b,c,g);break;case 8:this.g[3]=b/100,this.m(this.$a.gain,b/100,c,g)}}};self.oe=class extends d{constructor(a,b,c,g,l,t,e){super(a);this.O="phaser";this.g=[b,c,g,l,t,e];this.l=this.o();this.a=this.o();this.a.gain.value=1-e/2;this.b=this.o();this.b.gain.value=e/2;this.u=this.f.createBiquadFilter();this.u.type="allpass";this.u.frequency.value=b;this.u.detune.value=
c;this.u.Q.value=g;this.s=this.f.createOscillator();this.s.frequency.value=t;this.G=this.o();this.G.gain.value=l;this.l.connect(this.u);this.l.connect(this.a);this.u.connect(this.b);this.s.connect(this.G);this.G.connect(this.u.frequency);this.s.start(0)}c(){this.s.stop(0);this.l.disconnect();this.u.disconnect();this.s.disconnect();this.G.disconnect();this.a.disconnect();this.b.disconnect();super.c()}P(a){this.b.disconnect();this.b.connect(a);this.a.disconnect();this.a.connect(a)}N(){return this.l}Y(a,
b,c,g){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[5]=b;this.m(this.b.gain,b/2,c,g);this.m(this.a.gain,1-b/2,c,g);break;case 1:this.g[0]=b;this.m(this.u.frequency,b,c,g);break;case 2:this.g[1]=b;this.m(this.u.detune,b,c,g);break;case 3:this.g[2]=b;this.m(this.u.Q,b,c,g);break;case 6:this.g[3]=b;this.m(this.G.gain,b,c,g);break;case 7:this.g[4]=b,this.m(this.s.frequency,b,c,g)}}};self.ne=class extends d{constructor(a,b){super(a);this.O="gain";this.g=[b];this.h=this.o();this.h.gain.value=
b}c(){this.h.disconnect();super.c()}P(a){this.h.disconnect();this.h.connect(a)}N(){return this.h}Y(a,b,c,g){const l=self.da.hd;switch(a){case 4:this.g[0]=l(b),this.m(this.h.gain,l(b),c,g)}}};self.qe=class extends d{constructor(a,b,c){super(a);this.O="tremolo";this.g=[b,c];this.h=this.o();this.h.gain.value=1-c/2;this.s=this.f.createOscillator();this.s.frequency.value=b;this.G=this.o();this.G.gain.value=c/2;this.s.connect(this.G);this.G.connect(this.h.gain);this.s.start(0)}c(){this.s.stop(0);this.s.disconnect();
this.G.disconnect();this.h.disconnect();super.c()}P(a){this.h.disconnect();this.h.connect(a)}N(){return this.h}Y(a,b,c,g){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[1]=b;this.m(this.h.gain.value,1-b/2,c,g);this.m(this.G.gain.value,b/2,c,g);break;case 7:this.g[0]=b,this.m(this.s.frequency,b,c,g)}}};self.pe=class extends d{constructor(a,b,c){super(a);this.O="ringmod";this.g=[b,c];this.l=this.o();this.b=this.o();this.b.gain.value=c;this.a=this.o();this.a.gain.value=1-c;this.mb=this.o();
this.mb.gain.value=0;this.s=this.f.createOscillator();this.s.frequency.value=b;this.s.connect(this.mb.gain);this.s.start(0);this.l.connect(this.mb);this.l.connect(this.a);this.mb.connect(this.b)}c(){this.s.stop(0);this.s.disconnect();this.mb.disconnect();this.l.disconnect();this.b.disconnect();this.a.disconnect();super.c()}P(a){this.b.disconnect();this.b.connect(a);this.a.disconnect();this.a.connect(a)}N(){return this.l}Y(a,b,c,g){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[1]=b;this.m(this.b.gain,
b,c,g);this.m(this.a.gain,1-b,c,g);break;case 7:this.g[0]=b,this.m(this.s.frequency,b,c,g)}}};self.ke=class extends d{constructor(a,b,c,g,l,t){super(a);this.O="distortion";this.g=[b,c,g,l,t];this.l=this.o();this.Vb=this.o();this.Ub=this.o();this.cg(g,l);this.b=this.o();this.b.gain.value=t;this.a=this.o();this.a.gain.value=1-t;this.Zb=this.f.createWaveShaper();this.Kc=new Float32Array(65536);this.kf(b,c);this.Zb.curve=this.Kc;this.l.connect(this.Vb);this.l.connect(this.a);this.Vb.connect(this.Zb);
this.Zb.connect(this.Ub);this.Ub.connect(this.b)}c(){this.l.disconnect();this.Vb.disconnect();this.Zb.disconnect();this.Ub.disconnect();this.b.disconnect();this.a.disconnect();super.c()}cg(a,b){.01>a&&(a=.01);this.Vb.gain.value=a;this.Ub.gain.value=Math.pow(1/a,.6)*b}kf(a,b){for(let c=0;32768>c;++c){let g=c/32768;g=this.pg(g,a,b);this.Kc[32768+c]=g;this.Kc[32768-c-1]=-g}}pg(a,b,c){c=1.05*c*b-b;const g=0>a?-a:a;return(g<b?g:b+c*self.da.Hg(g-b,1/c))*(0>a?-1:1)}P(a){this.b.disconnect();this.b.connect(a);
this.a.disconnect();this.a.connect(a)}N(){return this.l}Y(a,b,c,g){switch(a){case 0:b=Math.max(Math.min(b/100,1),0),this.g[4]=b,this.m(this.b.gain,b,c,g),this.m(this.a.gain,1-b,c,g)}}};self.he=class extends d{constructor(a,b,c,g,l,t){super(a);this.O="compressor";this.g=[b,c,g,l,t];this.h=this.f.createDynamicsCompressor();this.h.threshold.value=b;this.h.knee.value=c;this.h.ratio.value=g;this.h.attack.value=l;this.h.release.value=t}c(){this.h.disconnect();super.c()}P(a){this.h.disconnect();this.h.connect(a)}N(){return this.h}Y(){}};
self.ge=class extends d{constructor(a,b,c){super(a);this.O="analyser";this.g=[b,c];this.h=this.f.createAnalyser();this.h.fftSize=b;this.h.smoothingTimeConstant=c;this.Nd=new Float32Array(this.h.frequencyBinCount);this.$d=new Uint8Array(b);this.Yd=this.Ia=0;this.i.Ue(this)}c(){this.i.Vf(this);this.h.disconnect();super.c()}ta(){this.h.getFloatFrequencyData(this.Nd);this.h.getByteTimeDomainData(this.$d);const a=this.h.fftSize;let b=this.Ia=0;for(var c=0;c<a;++c){let g=(this.$d[c]-128)/128;0>g&&(g=-g);
this.Ia<g&&(this.Ia=g);b+=g*g}c=self.da.Je;this.Ia=c(this.Ia);this.Yd=c(Math.sqrt(b/a))}P(a){this.h.disconnect();this.h.connect(a)}N(){return this.h}Y(){}Ae(){return{tag:this.$,index:this.Pd,peak:this.Ia,rms:this.Yd,binCount:this.h.frequencyBinCount,freqBins:this.Nd}}}}"use strict";
async function la(){const d=[],a=[];if(navigator.mediaDevices&&navigator.mediaDevices.enumerateDevices){var b=await navigator.mediaDevices.enumerateDevices();for(const c of b){b=c.kind;const g={deviceId:c.deviceId,label:c.label,facing:c.facing||c.facingMode||""};"video"===b||"videoinput"===b?d.push(g):("audio"===b||"audioinput"===b)&&a.push(g)}}return{videoSources:d,audioSources:a}}
async function ma(d,a,b){try{const c=d.v;"object"===typeof b.constraints.audio?await c.mc("CAMERA","RECORD_AUDIO","MODIFY_AUDIO_SETTINGS"):await c.mc("CAMERA");d.xa=await navigator.mediaDevices.getUserMedia(b.constraints);a.srcObject=d.xa;a.play();d.Rd&&C(d);return{ok:!0}}catch(c){return console.warn("Error requesting camera: ",c),{ok:!1}}}
async function na(d,a){try{return await d.v.mc("RECORD_AUDIO","MODIFY_AUDIO_SETTINGS"),d.xa=await navigator.mediaDevices.getUserMedia(a.constraints),self.C3Audio_OnMicrophoneStream&&self.C3Audio_OnMicrophoneStream(d.xa,a.tag),{ok:!0}}catch(b){return console.warn("Error requesting microphone: ",b),{ok:!1}}}
async function oa(d,a){const b=document.createElement("canvas");b.width=d.videoWidth;b.height=d.videoHeight;b.getContext("2d").drawImage(d,0,0,d.videoWidth,d.videoHeight);return{snapshotUrl:await pa(b,a.format,a.quality)}}function T(d,a){d.xa===a&&(d.xa=null);d=a.getTracks();for(let b=0,c=d.length;b<c;++b)d[b].stop()}function pa(d,a,b){return new Promise(c=>{d.toBlob?d.toBlob(g=>c(URL.createObjectURL(g)),a,b):c(d.toDataURL(a,b))})}
self.ka.qa(class extends self.qb{constructor(d){super(d,"user-media");this.Va=!1;this.Rd=this.v.Aa;this.Eg=0;this.xa=null;A(this,"get-media-sources",()=>la());G(this,"request-camera",(a,b)=>ma(this,a,b));G(this,"request-microphone",(a,b)=>na(this,b));G(this,"snapshot",(a,b)=>oa(a,b));G(this,"stop",a=>this.Hc(a));self.C3UserMedia_GetVideoElement=a=>this.T.get(a);self.C3UserMedia_GetLastMediaStream=()=>this.xa}Pa(d){const a=document.createElement("video");a.crossOrigin="anonymous";a.autoplay=!0;a.muted=
!0;a.playsInline=!0;a.addEventListener("canplaythrough",()=>{F(this,"video-ready",d,{width:a.videoWidth,height:a.videoHeight})});return a}ma(){}jd(d){d.srcObject&&(T(this,d.srcObject),d.srcObject=null)}Hc(d){d.srcObject&&(T(this,d.srcObject),d.srcObject=null)}ta(){if(this.Rd){var d={},a={sequenceNumber:this.Eg++,videoData:d},b=[],c=[];for(const [g,l]of this.T.entries()){if(!l.srcObject)continue;const t={};c.push(createImageBitmap(l).then(e=>{t.imageBitmap=e;b.push(e)}).catch(()=>{t.imageBitmap=null}));
d[g.toString()]=t}Promise.all(c).then(()=>v(this,"state",a,!1,b))}}});"use strict";function U(d){d.stopPropagation()}function V(d){const a=document.createElement("option");a.text=d;return a}function W(d){const a=d.selectedIndex,b=[];for(let c=0,g=d.length;c<g;++c)d.options[c].selected&&b.push(c);return{selectedIndex:a,selectedIndices:b}}
self.ka.qa(class extends self.qb{constructor(d){super(d,"list");G(this,"set-selected-index",(a,b)=>{a.selectedIndex=b.selectedIndex});G(this,"add-item",(a,b)=>{{const c=b.index;b=V(b.text);0>c?a.add(b):a.add(b,c)}});G(this,"remove-item",(a,b)=>{a.remove(b.index)});G(this,"set-item",(a,b)=>{a.options[b.index].text=b.text});G(this,"clear",a=>{a.innerHTML=""});G(this,"load-state",(a,b)=>this.Bc(a,b))}Pa(d,a){const b=a.isDropdown,c=a.isMultiSelect,g=a.items,l=document.createElement("select");l.style.position=
"absolute";l.style.userSelect="none";l.style.webkitUserSelect="none";l.multiple=c;b||(l.size=2);for(const t of g)l.add(V(t));l.addEventListener("touchstart",U);l.addEventListener("touchmove",U);l.addEventListener("touchend",U);l.addEventListener("mousedown",U);l.addEventListener("mouseup",U);l.addEventListener("click",t=>{t.stopPropagation();H(this,"click",d,W(l))});l.addEventListener("dblclick",t=>{t.stopPropagation();H(this,"dblclick",d,W(l))});l.addEventListener("change",()=>F(this,"change",d,
W(l)));a.id&&(l.id=a.id);this.ma(l,a);return l}ma(d,a){d.title=a.title;d.disabled=!a.isEnabled;d.multiple=!!a.isMultiSelect}Bc(d,a){d.innerHTML="";for(const b of a.items)d.add(V(b));d.selectedIndex=a.selectedIndex;for(const b of a.selectedIndices)if(a=d.options[b])a.selected=!0}});"use strict";function X(d){d.stopPropagation()}
self.ka.qa(class extends self.qb{constructor(d){super(d,"button")}Pa(d,a){const b=document.createElement("input");var c=b;a.isCheckbox?(b.type="checkbox",c=document.createElement("label"),c.appendChild(b),c.appendChild(document.createTextNode("")),c.style.fontFamily="sans-serif",c.style.userSelect="none",c.style.webkitUserSelect="none",c.style.display="inline-block",c.style.color="black"):b.type="button";c.style.position="absolute";c.addEventListener("touchstart",X);c.addEventListener("touchmove",
X);c.addEventListener("touchend",X);c.addEventListener("mousedown",X);c.addEventListener("mouseup",X);c.addEventListener("keydown",X);c.addEventListener("keyup",X);b.addEventListener("click",()=>H(this,"click",d,{isChecked:b.checked}));a.id&&(b.id=a.id);this.ma(c,a);return c}ma(d,a){const b="input"===d.tagName.toLowerCase()?d:d.firstChild;b.checked=a.isChecked;b.disabled=!a.isEnabled;d.title=a.title;d===b?b.value=a.text:d.lastChild.textContent=a.text}});"use strict";
self.ka.qa(class extends self.rb{constructor(d){super(d,"mouse");A(this,"cursor",a=>{document.documentElement.style.cursor=a})}});"use strict";function Y(d){13!==d.which&&27!==d.which&&d.stopPropagation()}function Z(d){d.stopPropagation()}
self.ka.qa(class extends self.qb{constructor(d){super(d,"text-input");G(this,"scroll-to-bottom",a=>{a.scrollTop=a.scrollHeight})}Pa(d,a){let b;const c=a.type;"textarea"===c?(b=document.createElement("textarea"),b.style.resize="none"):(b=document.createElement("input"),b.type=c);b.style.position="absolute";b.autocomplete="off";b.addEventListener("touchstart",Z);b.addEventListener("touchmove",Z);b.addEventListener("touchend",Z);b.addEventListener("mousedown",Z);b.addEventListener("mouseup",Z);b.addEventListener("keydown",
Y);b.addEventListener("keyup",Y);b.addEventListener("click",g=>{g.stopPropagation();H(this,"click",d)});b.addEventListener("dblclick",g=>{g.stopPropagation();H(this,"dblclick",d)});b.addEventListener("input",()=>F(this,"change",d,{text:b.value}));a.id&&(b.id=a.id);this.ma(b,a);return b}ma(d,a){d.value=a.text;d.placeholder=a.placeholder;d.title=a.title;d.disabled=!a.isEnabled;d.readOnly=a.isReadOnly;d.spellcheck=a.spellCheck;a=a.maxLength;0>a?d.removeAttribute("maxlength"):d.setAttribute("maxlength",
a)}});